<script setup>
import { language, t as tr, setLanguage, dateLabel } from './i18n.mjs'
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { Button, Badge, Dialog } from 'frappe-ui'
import { Boxes, LayoutList, CalendarClock, Ship, ShieldAlert, ChartNoAxesCombined, Database, Search, ArrowUpRight, ArrowRight, ChevronRight, Check, CheckCheck, Clock3, CircleHelp, RefreshCw, Download, Plus, X, LockKeyhole, MessageSquare, PackageCheck, Factory, Plane, CircleAlert, PanelLeftClose } from 'lucide-vue-next'
import { TODAY, fmt, daysLate, openQty, canSee, validateCommitment, seedOrders, seedIssues, seedShipments } from './domain.mjs'
import Overview from './Overview.vue'
import { money } from './analytics.mjs'
import { translate } from './translations.mjs'

const orders=ref(seedOrders()), issues=ref(seedIssues()), shipments=ref(seedShipments())
const page=ref('overview'), role=ref('buyer'), query=ref(''), filter=ref('open'), type=ref('全部类型'), mode=ref('全部运输'), buyer=ref('全部采购员')
const overviewSelection=ref(null)
const selected=ref(null), detailOpen=ref(false), detailTab=ref('overview'), modal=ref(''), modalOpen=ref(false), error=ref(''), notice=ref(''), sidebar=ref(false)
const comment=ref(''), response=ref('confirm'), batches=ref([]), reason=ref(''), issueStatus=ref('处理中'), activeIssue=ref(null), activeShipment=ref(null), shipmentStage=ref(2), shipmentLocation=ref(''), shipmentEta=ref('')
let toastTimer
const nav=[{id:'overview',title:'总览看板',icon:ChartNoAxesCombined},{id:'orders',title:'订单工作台',icon:LayoutList},{id:'delivery',title:'交期与承诺',icon:CalendarClock},{id:'shipments',title:'发运与物流',icon:Ship},{id:'exceptions',title:'异常与待办',icon:ShieldAlert},{id:'reports',title:'履约分析',icon:ChartNoAxesCombined},{id:'data',title:'数据中心',icon:Database}]
const titles={orders:['订单工作台','从订单确认到交付，所有协作在这里发生。'],delivery:['交期与承诺','关注交付变化，保留每一次承诺。'],shipments:['发运与物流','按批次跟进运输，连接订单与到货。'],exceptions:['异常与待办','把风险交给明确的责任人，持续跟进结果。'],reports:['履约分析','回顾历史表现，定位交付问题与改善方向。'],data:['数据中心','SAP 持续同步，平台维护协作数据。']}
const visible=computed(()=>orders.value.filter(o=>canSee(o,role.value)))
titles.overview=['总览看板','掌握订单、在途货物与交付风险。']
const visibleIssues=computed(()=>issues.value.filter(i=>visible.value.some(o=>o.id===i.order)))
const activeIssues=computed(()=>visibleIssues.value.filter(i=>i.status!=='已解决'))
const visibleShipments=computed(()=>shipments.value.filter(s=>visible.value.some(o=>o.id===s.order)))
const pending=computed(()=>visible.value.filter(o=>o.pending))
const unconfirmed=computed(()=>visible.value.filter(o=>!o.confirmed))
const openOrders=computed(()=>visible.value.filter(o=>openQty(o)>0))
const stats=computed(()=>[
  {label:'未完成订单',value:new Set(openOrders.value.map(o=>o.po)).size,unit:'张 PO',sub:`${openOrders.value.length} 个订单行`,icon:LayoutList,key:'open'},
  {label:'待供应商确认',value:unconfirmed.value.length,unit:'行',sub:'等待数量与交期承诺',icon:Clock3,key:'unconfirmed'},
  {label:'交期风险',value:visible.value.filter(o=>daysLate(o)>0&&openQty(o)>0).length,unit:'行',sub:'预计到仓晚于需求日期',icon:CalendarClock,key:'risk'},
  {label:'在途数量',value:visible.value.reduce((n,o)=>n+Math.max(0,o.shipped-o.received),0),unit:'件',sub:`${visibleShipments.value.length} 个发运批次`,icon:Ship,key:'transit'},
])
const filtered=computed(()=>visible.value.filter(o=>{
  const match=`${o.po} ${o.part} ${o.name} ${o.en} ${o.supplier}`.toLowerCase().includes(query.value.toLowerCase())
  return match&&(!overviewSelection.value||overviewSelection.value.ids.includes(o.id))&&(type.value==='全部类型'||o.type===type.value)&&(mode.value==='全部运输'||o.mode===mode.value)&&(buyer.value==='全部采购员'||o.buyer===buyer.value)&&
  (filter.value==='all'||(filter.value==='open'&&openQty(o)>0)||(filter.value==='unconfirmed'&&!o.confirmed)||(filter.value==='risk'&&daysLate(o)>0&&openQty(o)>0)||(filter.value==='transit'&&o.shipped>o.received)||(filter.value==='received'&&openQty(o)===0))
}))
const deliveryOrders=computed(()=>visible.value.filter(o=>openQty(o)>0).sort((a,b)=>(Number(!!b.pending)-Number(!!a.pending))||daysLate(b)-daysLate(a)))
const statusTheme=o=>o.pending?'orange':o.status==='待确认'?'orange':o.status==='已收货'?'green':o.status==='在途'||o.status==='部分发运'?'blue':'gray'
const selectedIssues=computed(()=>selected.value?issues.value.filter(i=>i.order===selected.value.id):[])
const selectedShipments=computed(()=>selected.value?shipments.value.filter(s=>s.order===selected.value.id):[])
const modalTitle=computed(()=>({response:'供应商订单响应',eta:'提交交期变更',resolve:'处理异常',shipment:'更新物流进展',reset:'重置演示数据',help:'如何体验这个预览',reject:'退回交期变更'}[modal.value]||'协作操作'))
const scopeLabel=computed(()=>role.value==='buyer'?'全部供应商':'Longtree 专属视图')

function toast(text){notice.value=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>notice.value='',4200)}
function navigate(id){if(id==='data'&&role.value!=='buyer')return;page.value=id;sidebar.value=false;detailOpen.value=false}
function inspectOverview(selection){overviewSelection.value=selection;query.value='';type.value='全部类型';mode.value='全部运输';buyer.value='全部采购员';filter.value='all';navigate('orders')}
watch(role,()=>overviewSelection.value=null)
function openOrder(order,tab='overview'){selected.value=order;detailTab.value=tab;detailOpen.value=true;comment.value=''}
function openModal(kind){modal.value=kind;error.value='';reason.value='';modalOpen.value=true}
function startResponse(){response.value='confirm';batches.value=[{qty:openQty(selected.value),date:selected.value.eta||selected.value.required}];openModal('response')}
function startEta(){batches.value=selected.value.batches.map(b=>({...b}));if(!batches.value.length)batches.value=[{qty:openQty(selected.value),date:selected.value.required}];openModal('eta')}
function stamp(){return '09/08 '+new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}
function addEvent(order,text,english){if(english)text={zh:text,en:english};order.history.unshift({who:role.value==='buyer'?'Regent · 采购':'Longtree · 供应商',time:stamp(),text})}
function submitResponse(){try{
  const order=selected.value
  if(role.value!=='supplier'||!canSee(order,role.value))throw new Error('请切换到 Longtree 供应商视角进行响应。')
  if(order.confirmed)throw new Error('该订单已确认，请使用交期变更。')
  if(response.value!=='confirm'){
    if(!reason.value.trim())throw new Error('请填写原因，便于采购跟进。')
    order.status=response.value==='reject'?'无法供货':'请求调整';
    const existing=issues.value.find(i=>i.order===order.id&&i.category==='供应商响应'&&i.status!=='已解决')
    if(existing){existing.detail=reason.value.trim();existing.userEntered=true;existing.title={zh:order.status+' · '+order.name,en:translate(order.status,'en')+' · '+order.en}}
    else issues.value.unshift({id:`EX-${issues.value.length+1}`,order:order.id,category:'供应商响应',title:{zh:order.status+' · '+order.name,en:translate(order.status,'en')+' · '+order.en},userEntered:true,detail:reason.value.trim(),owner:order.buyer,priority:'高',status:'待处理',note:'',due:'2026-09-09'})
    addEvent(order,order.status+'：'+reason.value.trim(),translate(order.status,'en')+': '+reason.value.trim())
  }else{
    const result=validateCommitment(order,batches.value)
    if(result.partial&&!reason.value.trim())throw new Error('部分确认时，请说明剩余数量的处理计划。')
    order.batches=batches.value.map(b=>({qty:Number(b.qty),date:b.date}));order.eta=result.eta;order.originalEta ||=result.eta;order.confirmed=true;order.status=result.partial?'部分确认':'已确认'
    addEvent(order,`已${result.partial?'部分':''}确认 ${result.total} 件，分 ${order.batches.length} 批交付。${reason.value}`,`${result.partial?'Partially confirmed':'Confirmed'} ${result.total} units across ${order.batches.length} batches. ${reason.value}`)
    if(result.partial) issues.value.unshift({id:`EX-${issues.value.length+1}`,order:order.id,category:'部分确认',title:`剩余 ${openQty(order)-result.total} 件待承诺`,userEntered:true,detail:reason.value,owner:order.buyer,priority:'中',status:'待处理',note:'',due:'2026-09-10'})
  }
  modalOpen.value=false;detailTab.value='commitment';toast('响应已记录，采购视角已同步更新。')
}catch(e){error.value=e.message}}
function submitEta(){try{
  const o=selected.value
  if(!o.confirmed||o.shipped>0)throw new Error('仅支持对已确认且未发运订单提交变更。')
  if(o.pending)throw new Error('已有一项交期变更等待采购审核。')
  if(!reason.value.trim())throw new Error('请填写交期变更原因。')
  const result=validateCommitment(o,batches.value)
  o.pending={batches:batches.value.map(b=>({qty:Number(b.qty),date:b.date})),eta:result.eta,reason:reason.value.trim(),who:role.value==='supplier'?'Longtree':'Regent 代录'}
  addEvent(o,`提出交期变更：${o.eta} → ${result.eta}。原因：${reason.value}`,`Date change proposed: ${o.eta} → ${result.eta}. Reason: ${reason.value}`);modalOpen.value=false;toast('变更已提交；采购接受前，原承诺保持有效。')
}catch(e){error.value=e.message}}
function approve(o){if(role.value!=='buyer'||!o.pending)return;const p=o.pending;o.eta=p.eta;o.batches=p.batches;o.pending=null;addEvent(o,`采购接受交期变更，新预计到仓日期 ${o.eta}`);toast('已接受变更，交期视图和报表已更新。')}
function rejectChange(){if(!reason.value.trim()){error.value='请填写退回原因。';return}if(role.value!=='buyer'||!selected.value?.pending)return;addEvent(selected.value,'采购退回交期变更：'+reason.value,'Buyer returned date change: '+reason.value);selected.value.pending=null;modalOpen.value=false;toast('已退回变更，保留原交付承诺。')}
function sendComment(){if(!comment.value.trim())return;selected.value.comments.unshift({who:role.value==='buyer'?'Regent · 采购':'Longtree · 供应商',time:stamp(),userEntered:true,text:comment.value.trim()});addEvent(selected.value,'添加了订单沟通记录');comment.value='';toast('留言已加入订单记录。')}
function startIssue(i){activeIssue.value=i;issueStatus.value=i.status==='已解决'?'处理中':i.status;openModal('resolve');reason.value=i.note||''}
function saveIssue(){if(role.value!=='buyer')return;if(!reason.value.trim()){error.value='请填写处理记录或关闭依据。';return}activeIssue.value.status=issueStatus.value;activeIssue.value.note=reason.value.trim();activeIssue.value.noteUserEntered=true;addEvent(orders.value.find(o=>o.id===activeIssue.value.order),`${activeIssue.value.id} ${issueStatus.value}：${reason.value}`,`${activeIssue.value.id} ${translate(issueStatus.value,'en')}: ${reason.value}`);modalOpen.value=false;toast('处理记录已更新。订单事实与交期风险按实际数据计算。')}
function startShipment(s){activeShipment.value=s;shipmentStage.value=s.stage;shipmentLocation.value=s.location;shipmentEta.value=s.eta;openModal('shipment')}
function saveShipment(){if(!shipmentLocation.value.trim()||!shipmentEta.value){error.value='请补充当前位置与预计到仓日期。';return}if(shipmentEta.value<TODAY){error.value='预计到仓日期不能早于演示业务日期。';return}Object.assign(activeShipment.value,{stage:Number(shipmentStage.value),location:shipmentLocation.value.trim(),locationUserEntered:true,eta:shipmentEta.value,updated:stamp()});addEvent(orders.value.find(o=>o.id===activeShipment.value.order),'更新物流节点：'+shipmentLocation.value+'；运输预计到仓 '+shipmentEta.value,'Shipment update: '+shipmentLocation.value+'; warehouse ETA '+shipmentEta.value);modalOpen.value=false;toast('物流进展已更新；正式发货与收货记录仍以 SAP 为准。')}
function exportOrders(){const quote=s=>'"'+String(s).replaceAll('"','""')+'"';const csv='\uFEFF'+[['PO','订单行','物料编码','供应商','订购数量','已收数量','未交数量','需求日期','承诺到仓','状态'],...filtered.value.map(o=>[o.po,o.item,o.part,o.supplier,o.qty,o.received,openQty(o),o.required,o.eta,o.status])].map(r=>r.map(value=>quote(tr(value))).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=tr('Regent-演示订单.csv');a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('已导出当前筛选范围的演示订单。')}
function reset(){overviewSelection.value=null;orders.value=seedOrders();issues.value=seedIssues();shipments.value=seedShipments();selected.value=null;detailOpen.value=false;modalOpen.value=false;query.value='';filter.value='open';toast('演示已恢复初始状态。')}
watch(role,()=>{selected.value=null;detailOpen.value=false;modalOpen.value=false;buyer.value='全部采购员';if(page.value==='data')page.value='orders';toast(role.value==='supplier'?'已切换：Longtree 供应商，只展示本供应商的模拟订单。':'已切换：Regent 内部采购，可审核变更和处理异常。')})
onUnmounted(()=>clearTimeout(toastTimer))
const toolLifecycle=new AbortController()
onMounted(()=>{
  const context=document.modelContext
  if(!context?.registerTool)return
  const tools=[
    {name:'read_demo_orders',description:'Read the fictional orders visible to the current demo role.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>visible.value.map(o=>({id:o.id,po:o.po,part:o.part,status:o.status,eta:o.eta,openQty:openQty(o)}))},
    {name:'open_demo_order',description:'Open an order detail in the current demo role. Does not modify the order.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||typeof input.id!=='string')throw new Error('An order id is required');const order=visible.value.find(o=>o.id===input.id);if(!order)throw new Error('Order not available in current demo scope');openOrder(order);await nextTick();return {opened:order.id}}},
  ]
  for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:toolLifecycle.signal})).catch(()=>{})}catch{}}
})
onUnmounted(()=>toolLifecycle.abort())
</script>

<template>
  <div class="workspace" :class="{'overview-layout':page==='overview'}">
    <aside class="sidebar" :class="{mobileOpen:sidebar}">
      <a class="brand" href="#/" @click.prevent="navigate('overview')"><span class="brandmark"><Boxes :size="23"/></span><span>REGENT<small>SUPPLIER COLLABORATION</small></span></a>
      <div class="workspace-label">{{tr("采购与供应商协作")}} <span>AU / CN</span></div>
      <nav :aria-label="tr(&quot;主要导航&quot;)"><button v-for="n in nav.filter(n=>role==='buyer'||n.id!=='data')" :key="n.id" :class="['navitem',{active:page===n.id}]" @click="navigate(n.id)"><component :is="n.icon" :size="19"/><span>{{tr(n.title)}}</span><span v-if="n.id==='exceptions'&&activeIssues.length" class="navcount">{{tr(activeIssues.length)}}</span></button></nav>
      <div class="sidebar-bottom"><div class="connection"><span class="live-dot"></span><div>{{tr("SAP + 协作平台")}}<small>{{tr("演示环境 · 业务日期 09/08")}}</small></div></div><button class="help-link" @click="openModal('help')"><CircleHelp :size="17"/> {{tr("预览说明")}} <ArrowUpRight :size="15"/></button><a href="https://github.com/frappe/frappe-ui" target="_blank" rel="noreferrer" class="powered">Built with Frappe UI ↗</a></div>
    </aside>
    <div class="main-shell">
      <header class="topbar"><div class="crumb"><button class="mobile-menu" :aria-label="tr(&quot;展开导航&quot;)" @click="sidebar=!sidebar"><PanelLeftClose :size="20"/></button><span>{{tr("供应商协作")}}</span><ChevronRight :size="14"/><strong>{{tr(titles[page][0])}}</strong></div><div class="topbar-right"><span class="demo-chip">{{tr("功能预览 · 模拟数据")}}</span><div class="language-switch" role="group" :aria-label="tr('语言切换')"><button type="button" lang="zh-CN" :aria-pressed="language==='zh'" @click="setLanguage('zh')">中文</button><button type="button" lang="en" :aria-pressed="language==='en'" @click="setLanguage('en')">English</button></div><label class="role-select"><span class="avatar">{{tr(role==='buyer'?'R':'L')}}</span><select v-model="role" :aria-label="tr(&quot;切换演示角色&quot;)"><option value="buyer">{{tr("Regent · 内部采购")}}</option><option value="supplier">{{tr("Longtree · 供应商")}}</option></select></label></div></header>
      <main :class="{'overview-main':page==='overview'}">
        <div v-if="page!=='overview'" class="page-heading"><div><div class="eyebrow">{{tr(scopeLabel)}}<span> / </span> ORDER COLLABORATION</div><h1>{{tr(titles[page][0])}}</h1><p>{{tr(titles[page][1])}}</p></div><div class="heading-actions"><Button variant="outline" size="lg" @click="openModal('reset')"><template #prefix><RefreshCw :size="15"/></template>{{tr("重置演示")}}</Button><Button v-if="page==='orders'" variant="solid" class="primary" size="lg" @click="exportOrders"><template #prefix><Download :size="15"/></template>{{tr("导出当前视图")}}</Button></div></div>

        <Overview v-if="page==='overview'" :orders="visible" :shipments="visibleShipments" :issues="visibleIssues" :role="role" @inspect="inspectOverview" @open-order="openOrder" @navigate="navigate" @reset="openModal('reset')"/>
        <template v-else-if="page==='orders'">
          <div v-if="overviewSelection" class="overview-selection"><span>{{tr("来自总览：")}}<strong>{{tr(overviewSelection.label)}}</strong> · {{tr(overviewSelection.ids.length)}} {{tr("行")}}</span><Button variant="ghost" @click="overviewSelection=null">{{tr("清除看板范围")}} <X :size="14"/></Button><Button variant="outline" @click="navigate('overview')">{{tr("返回总览")}}</Button></div>
          <div class="metric-grid"><button v-for="s in stats" :key="s.key" :class="['metric',{chosen:filter===s.key}]" @click="filter=s.key"><div class="metric-label">{{tr(s.label)}}<component :is="s.icon" :size="18"/></div><div class="metric-number">{{tr(fmt(s.value))}}<span>{{tr(s.unit)}}</span></div><div class="metric-foot">{{tr(s.sub)}}<ArrowUpRight :size="15"/></div></button></div>
          <div v-if="activeIssues.length||pending.length" class="attention"><span class="attention-icon"><CircleAlert :size="19"/></span><div><strong>{{tr(pending.length?`${pending.length} 项交期变更等待审核`:`${activeIssues.length} 项协作事项需要跟进`)}}</strong><span>{{tr(pending.length?'供应商提出了新的交付安排，原承诺在审核前继续有效。':'优先关注交期延误、物料编码与待订舱订单。')}}</span></div><button @click="navigate(pending.length?'delivery':'exceptions')">{{tr("查看待办")}} <ArrowRight :size="16"/></button></div>
          <section class="panel order-panel"><div class="tabs"><button v-for="t in [['open','未完成订单'],['unconfirmed','待确认'],['risk','交期风险'],['transit','在途'],['received','已收货'],['all','全部订单']]" :key="t[0]" :class="{selected:filter===t[0]}" @click="filter=t[0]">{{tr(t[1])}}<span v-if="t[0]==='unconfirmed'">{{tr(unconfirmed.length)}}</span></button></div>
            <div class="filters"><label class="searchbox"><Search :size="17"/><input v-model="query" :placeholder="tr(&quot;搜索 PO、物料编码或名称…&quot;)" :aria-label="tr(&quot;搜索订单&quot;)"/><button v-if="query" @click="query=''" :aria-label="tr(&quot;清空搜索&quot;)"><X :size="15"/></button></label><select v-model="type" :aria-label="tr(&quot;订单类型&quot;)"><option :value="&quot;全部类型&quot;">{{tr("全部类型")}}</option><option :value="&quot;生产订单&quot;">{{tr("生产订单")}}</option><option :value="&quot;售后配件&quot;">{{tr("售后配件")}}</option></select><select v-model="mode" :aria-label="tr(&quot;运输方式&quot;)"><option :value="&quot;全部运输&quot;">{{tr("全部运输")}}</option><option :value="&quot;海运&quot;">{{tr("海运")}}</option><option :value="&quot;空运&quot;">{{tr("空运")}}</option></select><select v-if="role==='buyer'" v-model="buyer" :aria-label="tr(&quot;采购员&quot;)"><option :value="&quot;全部采购员&quot;">{{tr("全部采购员")}}</option><option :value="&quot;Karen A.&quot;">Karen A.</option><option :value="&quot;Nishi A.&quot;">Nishi A.</option></select><span class="result-count">{{tr(filtered.length)}} {{tr("个订单行")}}</span></div>
            <div class="table-scroll"><table class="orders-table"><thead><tr><th>{{tr("订单 / 物料")}}</th><th>{{tr("供应商 / 类型")}}</th><th class="right">{{tr("订购 / 未交")}}</th><th>{{tr("需求 / 承诺到仓")}}</th><th>{{tr("履约进展")}}</th><th>{{tr("协作状态")}}</th><th></th></tr></thead><tbody><tr v-for="o in filtered" :key="o.id" @click="openOrder(o)"><td><button class="order-link" @click.stop="openOrder(o)">{{tr(o.po)}}<span>/ {{tr(o.item)}}</span></button><div class="material-name">{{tr(o.name)}}</div><small class="mono muted">{{tr(o.part)}}</small></td><td><strong class="supplier-name">{{tr(o.supplier)}}</strong><small>{{tr(o.type)}} · {{tr(o.buyer)}}</small></td><td class="right"><strong>{{tr(fmt(o.qty))}}</strong><small><span :class="{'teal-text':openQty(o)>0}">{{tr(fmt(openQty(o)))}} {{tr("未交")}}</span></small></td><td><span class="date-pair">{{tr(dateLabel(o.required))}}<ArrowRight :size="12"/><strong :class="{'danger-text':daysLate(o)>0}">{{tr(dateLabel(o.eta))}}</strong></span><small v-if="daysLate(o)>0" class="danger-text">{{tr("晚于需求")}} {{tr(daysLate(o))}} {{tr("天")}}</small><small v-else-if="o.eta">{{tr(o.mode)}} · {{tr(o.received===o.qty?'已完成':'交期正常')}}</small><small v-else>{{tr("待供应商承诺")}}</small></td><td><div class="progress-text"><span>{{tr(o.progress===100?'生产完成':o.progress?`生产 ${o.progress}%`:'尚未开始')}}</span><span>{{tr(o.progress)}}%</span></div><div class="progress-track"><i :style="{width:o.progress+'%'}"></i></div></td><td><Badge :theme="statusTheme(o)" size="lg">{{tr(o.pending?'变更待审核':o.status)}}</Badge></td><td><button class="row-arrow" :aria-label="tr(&quot;查看订单详情&quot;)" @click.stop="openOrder(o)"><ChevronRight :size="18"/></button></td></tr><tr v-if="!filtered.length"><td colspan="7" class="empty"><Search :size="28"/><strong>{{tr("没有匹配的订单")}}</strong><span>{{tr("试试其他关键词或筛选条件。")}}</span><Button variant="outline" @click="overviewSelection=null;query='';type='全部类型';mode='全部运输';buyer='全部采购员';filter='all'">{{tr("清除筛选")}}</Button></td></tr></tbody></table></div><footer class="table-footer"><span>{{tr("按 PO 订单行展示 · 数量单位：件")}}</span><span>{{tr("全部")}} {{tr(filtered.length)}} {{tr("行")}} <span class="page-box">1</span></span></footer>
          </section>
          <div class="source-note"><LockKeyhole :size="14"/> {{tr("SAP 订单数据只读；确认、承诺与沟通在平台维护。")}}<span>{{tr("本次演示操作在刷新后重置。")}}</span></div>
        </template>

        <template v-else-if="page==='delivery'">
          <div class="section-summary"><span><strong>{{tr(pending.length)}}</strong> {{tr("项变更待审核")}}</span><span><strong>{{tr(visible.filter(o=>daysLate(o)>0&&openQty(o)>0).length)}}</strong> {{tr("行存在交期风险")}}</span><span>{{tr("日期统一表示")}} <b>{{tr("预计到仓")}}</b></span></div>
          <section class="panel"><div class="panel-heading"><h2>{{tr("交付承诺")}}</h2><span class="muted">{{tr("需求 → 当前承诺 → 变更申请")}}</span></div><div v-for="o in deliveryOrders" :key="o.id" class="delivery-row"><div><button class="order-link" @click="openOrder(o,'commitment')">{{tr(o.po)}} <span>/ {{tr(o.item)}}</span></button><p>{{tr(o.name)}}</p><small>{{tr(o.supplier)}} · {{tr(o.buyer)}}</small></div><div class="date-block"><small>{{tr("SAP 需求到仓")}}</small><strong>{{tr(dateLabel(o.required))}}</strong></div><ArrowRight class="muted" :size="17"/><div class="date-block"><small>{{tr("当前承诺到仓")}}</small><strong :class="{'danger-text':daysLate(o)>0}">{{tr(dateLabel(o.eta))}}</strong></div><div class="delivery-status"><Badge v-if="o.pending" theme="orange" size="lg">{{tr("申请")}} {{tr(dateLabel(o.pending.eta))}}</Badge><Badge v-else-if="daysLate(o)>0" theme="red" size="lg">{{tr("延后")}} {{tr(daysLate(o))}} {{tr("天")}}</Badge><Badge v-else :theme="o.eta?'green':'gray'" size="lg">{{tr(o.eta?'按计划':'待确认')}}</Badge></div><Button variant="outline" @click="openOrder(o,'commitment')">{{tr(o.pending&&role==='buyer'?'审核变更':'查看安排')}}</Button></div></section>
        </template>

        <template v-else-if="page==='shipments'">
          <div class="shipment-grid"><section v-for="s in visibleShipments" :key="s.id" class="panel shipment-card"><div class="shipment-top"><span class="transport-icon"><component :is="s.mode==='海运'?Ship:Plane" :size="24"/></span><div><h2>{{tr(s.id)}}</h2><small>{{tr(s.mode)}} · {{tr(s.ref)}}</small></div><Badge theme="blue" size="lg">{{tr(['待出发','已离港','在途','已到港'][s.stage])}}</Badge></div><div class="route-line"><div><small>{{tr("起运地")}}</small><h3>{{tr(s.from)}}</h3><span>{{tr(dateLabel(s.etd))}} {{tr("出发")}}</span></div><div class="route-rule"><component :is="s.mode==='海运'?Ship:Plane" :size="20"/></div><div class="right"><small>{{tr("目的地")}}</small><h3>{{tr(s.to)}}</h3><span>{{tr(dateLabel(s.eta))}} {{tr("预计到仓")}}</span></div></div><div class="milestones"><div v-for="(label,i) in ['待出发','已离港','在途','已到港']" :class="{done:i<=s.stage}" :key="label"><span><Check v-if="i<s.stage" :size="12"/><i v-else></i></span>{{tr(label)}}</div></div><div class="shipment-info"><span>{{tr("当前位置")}}<strong>{{s.locationUserEntered?s.location:tr(s.location)}}</strong></span><span>{{tr("承运信息")}}<strong>{{tr(s.carrier)}}</strong></span><span>{{tr("发运数量")}}<strong>{{tr(fmt(s.qty))}} {{tr("件")}}</strong></span></div><footer><small>{{tr("模拟更新")}} {{tr(s.updated)}}</small><Button variant="outline" @click="startShipment(s)">{{tr("更新物流")}}</Button></footer><button class="shipment-order" @click="openOrder(orders.find(o=>o.id===s.order),'logistics')">{{tr("关联 PO")}} {{tr(s.order.replace('-',' / '))}} <ArrowUpRight :size="14"/></button></section></div><div class="info-box"><LockKeyhole :size="19"/><p>{{tr("平台维护运输节点及运输预计到仓时间。正式发货和收货数量由 SAP 同步；物流到港不等于 SAP 已收货。")}}</p></div>
        </template>

        <template v-else-if="page==='exceptions'">
          <div class="section-summary"><span><strong>{{tr(activeIssues.length)}}</strong> {{tr("项待跟进")}}</span><span><strong>{{tr(visibleIssues.filter(i=>i.status==='已解决').length)}}</strong> {{tr("项已解决")}}</span><span>{{tr("每项异常都有责任人与处理记录")}}</span></div><section class="panel"><article v-for="i in visibleIssues" :key="i.id" class="issue-card"><div class="issue-icon" :class="{resolved:i.status==='已解决'}"><CheckCheck v-if="i.status==='已解决'" :size="21"/><ShieldAlert v-else :size="21"/></div><div class="issue-main"><div class="issue-title"><h2>{{tr(i.title)}}</h2><Badge :theme="i.status==='已解决'?'green':i.priority==='高'?'red':'orange'">{{tr(i.status==='已解决'?'已解决':i.priority+'优先级')}}</Badge></div><p>{{i.userEntered?i.detail:tr(i.detail)}}</p><div class="issue-meta"><button @click="openOrder(orders.find(o=>o.id===i.order))">{{tr(i.order.replace('-',' / '))}}</button><span>{{tr(i.category)}}</span><span>{{tr("负责人")}} {{tr(i.owner)}}</span><span>{{tr("跟进截止")}} {{tr(dateLabel(i.due))}}</span></div><div v-if="i.note" class="issue-note">{{tr("处理记录：")}}{{i.noteUserEntered?i.note:tr(i.note)}}</div></div><div class="issue-action"><Badge theme="gray">{{tr(i.status)}}</Badge><Button v-if="role==='buyer'" variant="outline" @click="startIssue(i)">{{tr(i.status==='已解决'?'重新跟进':'处理异常')}}</Button><Button v-else variant="outline" @click="openOrder(orders.find(o=>o.id===i.order),'activity')">{{tr("补充说明")}}</Button></div></article></section>
        </template>

        <template v-else-if="page==='reports'">
          <section class="panel analysis-panel">
            <div class="analysis-intro"><ChartNoAxesCombined :size="26"/><div><h2>{{tr('历史履约分析')}}</h2><p>{{tr('当前演示仅包含订单快照，尚不足以计算历史绩效。接入完整记录后，将在这里按月、季度和供应商进行对比。')}}</p></div><Badge theme="gray">{{tr('待接入历史数据')}}</Badge></div>
            <div class="table-scroll"><table class="analysis-table"><thead><tr><th>{{tr('分析方向')}}</th><th>{{tr('关注的问题')}}</th><th>{{tr('所需历史记录')}}</th></tr></thead><tbody>
              <tr><td>{{tr('供应商响应效率')}}</td><td>{{tr('订单多久被确认，哪些供应商响应较慢')}}</td><td>{{tr('订单通知时间、首次响应与确认时间')}}</td></tr>
              <tr><td>{{tr('承诺兑现与交期变化')}}</td><td>{{tr('首次承诺是否兑现，交期为何反复调整')}}</td><td>{{tr('承诺版本、变更原因、实际到仓与收货记录')}}</td></tr>
              <tr><td>{{tr('运输表现与延期原因')}}</td><td>{{tr('运输耗时与 ETA 偏差主要集中在哪些环节')}}</td><td>{{tr('历史运输节点、ETA 版本及异常原因')}}</td></tr>
            </tbody></table></div>
            <footer class="analysis-footer"><span>{{tr('当前订单、在途数量和货值请查看总览；数据核对由数据中心负责。')}}</span><Button variant="outline" @click="navigate('overview')">{{tr('返回总览')}}</Button><Button v-if="role==='buyer'" variant="outline" @click="navigate('data')">{{tr('数据中心')}}</Button></footer>
          </section>
        </template>

        <template v-else-if="page==='data'&&role==='buyer'">
          <div class="data-flow"><div><Database :size="25"/><strong>SAP</strong><small>{{tr("正式订单 / 发货 / 收货")}}</small></div><ArrowRight :size="22"/><div class="central"><Boxes :size="26"/><strong>{{tr("协作平台")}}</strong><small>{{tr("确认 / 交期 / 沟通 / 异常")}}</small></div><ArrowRight :size="22"/><div><ChartNoAxesCombined :size="25"/><strong>{{tr("可信报表")}}</strong><small>{{tr("统一口径 / 数据可追溯")}}</small></div></div><section class="panel"><div class="panel-heading"><h2>{{tr("数据运行状态")}}</h2><Badge theme="green" size="lg">{{tr("模拟状态")}}</Badge></div><div class="data-row"><div><strong>{{tr("SAP 订单同步")}}</strong><small>{{tr("计划持续同步正式业务记录")}}</small></div><span>{{tr(orders.length)}} {{tr("个演示订单行")}}</span><Badge theme="green">{{tr("示例已载入")}}</Badge></div><div class="data-row"><div><strong>{{tr("待处理的数据问题")}}</strong><small>{{tr("在平台分派、核对和记录修正结果")}}</small></div><span>{{tr(issues.filter(i=>i.category==='数据问题'&&i.status!=='已解决').length)}} {{tr("项")}}</span><Button variant="outline" @click="navigate('exceptions')">{{tr("查看问题")}}</Button></div><div class="data-row"><div><strong>{{tr("平台协作记录")}}</strong><small>{{tr("供应商确认、交期变更和沟通")}}</small></div><span>{{tr(orders.reduce((n,o)=>n+o.history.length,0))}} {{tr("条事件")}}</span><Badge theme="green">{{tr("本次会话内更新")}}</Badge></div></section><section class="panel report-panel data-quantity"><h2>{{tr("数量核对")}}</h2><div class="quantity-grid"><div><small>{{tr("订购总量")}}</small><strong>{{tr(fmt(visible.reduce((n,o)=>n+o.qty,0)))}}<span>{{tr("件")}}</span></strong></div><div><small>{{tr("已收货 · SAP")}}</small><strong>{{tr(fmt(visible.reduce((n,o)=>n+o.received,0)))}}<span>{{tr("件")}}</span></strong></div><div><small>{{tr("在途 · 已发未收")}}</small><strong>{{tr(fmt(stats[3].value))}}<span>{{tr("件")}}</span></strong></div><div><small>{{tr("尚未发运")}}</small><strong>{{tr(fmt(visible.reduce((n,o)=>n+o.qty-o.shipped,0)))}}<span>{{tr("件")}}</span></strong></div></div><p class="muted">{{tr("本演示物料统一为“件”；正式系统需按计量单位分组。准时交付率需真实收货历史后再计算。")}}</p></section><section class="panel migration-panel"><div class="migration-check"><CheckCheck :size="22"/></div><div><h2>{{tr("初始迁移已完成")}} <Badge theme="gray">{{tr("演示场景")}}</Badge></h2><p>{{tr("历史 Excel 仅用于初次导入和核对。切换后，日常业务由 SAP 与平台维护。")}}</p><div class="migration-steps"><span>{{tr("01 导入历史数据")}}</span><ChevronRight :size="15"/><span>{{tr("02 核对与业务确认")}}</span><ChevronRight :size="15"/><strong>{{tr("03 切换平台协作 ✓")}}</strong></div><small>{{tr("尚未接入实际文件或 SAP；这里展示未来正式运行后的界面。")}}</small></div></section>
        </template>
      </main>
    </div>
    <div v-if="notice" class="toast" role="status"><Check :size="18"/>{{tr(notice)}}<button @click="notice=''" :aria-label="tr(&quot;关闭提示&quot;)"><X :size="15"/></button></div>

    <Dialog v-model="detailOpen" :options="{title:tr('订单详情'),size:'3xl'}"><template #body-content><div v-if="selected" class="order-detail"><div class="detail-title"><div><div class="eyebrow">PURCHASE ORDER / {{tr(selected.item)}}</div><h2>{{tr(selected.po)}}</h2><p>{{tr(selected.name)}}</p><small>{{tr(selected.part)}} · {{tr(selected.supplier)}}</small></div><Badge :theme="statusTheme(selected)" size="lg">{{tr(selected.pending?'变更待审核':selected.status)}}</Badge></div><div class="detail-tabs"><button v-for="t in [['overview','订单概览'],['commitment','交付承诺'],['logistics','发运记录'],['activity','沟通与历史']]" :key="t[0]" :class="{active:detailTab===t[0]}" @click="detailTab=t[0]">{{tr(t[1])}}</button></div>
      <div v-if="detailTab==='overview'" class="overview-price"><span>{{tr("示例单价 / AUD")}}<strong>{{tr(money(selected.unitPrice))}}<small> {{tr("/ 件")}}</small></strong></span><span>{{tr("未交货值 / AUD")}}<strong>{{tr(money(openQty(selected)*selected.unitPrice))}}</strong></span><small>{{tr("模拟采购价格 · 不含税费与运费")}}</small></div>
      <template v-if="detailTab==='overview'"><div class="read-only-label"><LockKeyhole :size="14"/> {{tr("SAP 数据 · 只读")}}</div><div class="detail-fields"><div><small>{{tr("物料描述")}}</small><strong>{{tr(selected.en)}}</strong></div><div><small>{{tr("采购员 / 工厂")}}</small><strong>{{tr(selected.buyer)}} / {{tr(selected.plant)}}</strong></div><div><small>{{tr("订购数量")}}</small><strong>{{tr(fmt(selected.qty))}} {{tr("件")}}</strong></div><div><small>{{tr("已收货 / 未交")}}</small><strong>{{tr(fmt(selected.received))}} / {{tr(fmt(openQty(selected)))}} {{tr("件")}}</strong></div><div><small>{{tr("订单类型")}}</small><strong>{{tr(selected.type)}}</strong></div><div><small>{{tr("需求到仓日期")}}</small><strong>{{tr(selected.required)}}</strong></div></div><div class="detail-subheading"><h3>{{tr("履约进展")}}</h3><span>{{tr("供应商反馈")}}</span></div><div class="production-progress"><Factory :size="21"/><div><strong>{{tr(selected.progress===100?'生产已完成':selected.progress?'正在生产':'尚未开始生产')}}</strong><div class="progress-track"><i :style="{width:selected.progress+'%'}"></i></div></div><b>{{tr(selected.progress)}}%</b></div><div v-for="i in selectedIssues.filter(i=>i.status!=='已解决')" :key="i.id" class="detail-alert"><CircleAlert :size="18"/><div><strong>{{tr(i.title)}}</strong><p>{{i.userEntered?i.detail:tr(i.detail)}}</p></div></div><div class="detail-bottom-action"><p>{{tr(role==='buyer'?'供应商响应可在右上角切换到供应商视角体验。':'请确认数量和预计到仓日期，或说明无法供货的原因。')}}</p><Button v-if="role==='supplier'&&!selected.confirmed" variant="solid" class="primary" size="lg" @click="startResponse">{{tr("响应订单")}}</Button><Button v-else variant="solid" class="primary" size="lg" @click="detailTab='commitment'">{{tr("查看交付承诺")}}</Button></div></template>
      <template v-if="detailTab==='commitment'"><div class="commitment-dates"><div><small>{{tr("需求到仓 · SAP")}}</small><strong>{{tr(dateLabel(selected.required))}}</strong></div><ArrowRight :size="18"/><div><small>{{tr("当前承诺 · 平台")}}</small><strong :class="{'danger-text':daysLate(selected)>0}">{{tr(dateLabel(selected.eta))}}</strong></div></div><div v-if="selected.pending" class="pending-change"><div><Badge theme="orange">{{tr("变更待审核")}}</Badge><strong>{{tr("申请到仓")}} {{tr(selected.pending.eta)}}</strong><p>{{selected.pending.reason}}</p><small>{{tr(selected.pending.who)}} {{tr("提出 · 当前承诺在审核前不变")}}</small></div><div v-if="role==='buyer'" class="button-row"><Button variant="outline" @click="openModal('reject')">{{tr("退回")}}</Button><Button variant="solid" class="primary" @click="approve(selected)">{{tr("接受变更")}}</Button></div></div><div class="detail-subheading"><h3>{{tr("分批交付安排")}}</h3><span>{{tr("已承诺")}} {{tr(fmt(selected.batches.reduce((n,b)=>n+b.qty,0)))}} {{tr("件")}}</span></div><div v-if="!selected.batches.length" class="mini-empty"><CalendarClock :size="27"/><p>{{tr("供应商尚未提交交付承诺")}}</p></div><div v-for="(b,index) in selected.batches" :key="index" class="batch-row"><span class="batch-number">{{tr(String(index+1).padStart(2,'0'))}}</span><div><small>{{tr("交付数量")}}</small><strong>{{tr(fmt(b.qty))}} {{tr("件")}}</strong></div><div><small>{{tr("预计到仓")}}</small><strong>{{tr(b.date)}}</strong></div><Badge theme="gray">{{tr(selected.mode)}}</Badge></div><p class="muted detail-hint">{{tr("交付批次表示数量与到仓承诺；实际发运记录单独跟踪。")}}</p><div class="button-row"><Button v-if="role==='supplier'&&!selected.confirmed" variant="solid" class="primary" size="lg" @click="startResponse">{{tr("响应订单 / 分批确认")}}</Button><Button v-if="selected.confirmed&&!selected.shipped&&!selected.pending" variant="solid" class="primary" size="lg" @click="startEta">{{tr("提交交期变更")}}</Button></div><p v-if="selected.shipped>0" class="info-box">{{tr("该订单已有发运，运输时间请在发运记录中跟进。")}}</p></template>
      <template v-if="detailTab==='logistics'"><div v-if="!selectedShipments.length" class="mini-empty"><Ship :size="32"/><h3>{{tr("暂无发运记录")}}</h3><p>{{tr("供应商反馈生产进展；正式发货记录由 SAP 同步。")}}</p></div><div v-for="s in selectedShipments" :key="s.id" class="detail-shipment"><div class="detail-subheading"><h3>{{tr(s.id)}}</h3><Badge theme="blue">{{tr(s.mode)}}</Badge></div><div class="detail-fields"><div><small>{{tr("集装箱 / 运单号")}}</small><strong>{{tr(s.ref)}}</strong></div><div><small>{{tr("发运数量")}}</small><strong>{{tr(s.qty)}} {{tr("件")}}</strong></div><div><small>{{tr("当前位置")}}</small><strong>{{s.locationUserEntered?s.location:tr(s.location)}}</strong></div><div><small>{{tr("运输预计到仓")}}</small><strong>{{tr(s.eta)}}</strong></div></div><Button variant="outline" @click="startShipment(s)">{{tr("更新物流进展")}}</Button></div></template>
      <template v-if="detailTab==='activity'"><div class="comment-compose"><label for="order-comment">{{tr("订单沟通")}}</label><textarea id="order-comment" v-model="comment" rows="3" :placeholder="tr(&quot;补充交期原因、跟进进展或供应商说明…&quot;)"></textarea><div><small>{{tr(role==='buyer'?'以 Regent 采购身份留言':'以 Longtree 供应商身份留言')}}</small><Button variant="solid" class="primary" :disabled="!comment.trim()" @click="sendComment">{{tr("发送留言")}}</Button></div></div><div v-for="(c,i) in selected.comments" :key="i" class="comment"><span class="comment-avatar"><MessageSquare :size="16"/></span><div><strong>{{tr(c.who)}}</strong><small>{{tr(c.time)}}</small><p>{{c.userEntered?c.text:tr(c.text)}}</p></div></div><h3 class="history-heading">{{tr("操作历史")}}</h3><div class="timeline"><div v-for="(e,i) in [...selected.history].sort((a,b)=>b.time.localeCompare(a.time))" :key="i"><i></i><small>{{tr(e.time)}} · {{tr(e.who)}}</small><p>{{tr(e.text)}}</p></div></div></template>
    </div></template></Dialog>

    <Dialog v-model="modalOpen" :options="{title:tr(modalTitle),size:modal==='help'?'xl':'lg'}"><template #body-content>
      <template v-if="modal==='response'||modal==='eta'"><div class="modal-context">{{tr(selected?.po)}} / {{tr(selected?.item)}}<strong>{{tr(selected?.name)}}</strong><span>{{tr("未交")}} {{tr(fmt(openQty(selected)))}} {{tr("件 · 需求到仓")}} {{tr(selected?.required)}}</span></div><div v-if="modal==='response'" class="response-options"><button v-for="r in [['confirm','确认供货'],['change','请求调整'],['reject','无法供货']]" :key="r[0]" :class="{active:response===r[0]}" @click="response=r[0]">{{tr(r[1])}}</button></div><template v-if="modal==='eta'||response==='confirm'"><div class="form-heading"><strong>{{tr(modal==='eta'?'新的交付安排':'交付安排')}}</strong><Button variant="ghost" @click="batches.push({qty:1,date:selected.required})"><template #prefix><Plus :size="14"/></template>{{tr("添加批次")}}</Button></div><div v-for="(b,i) in batches" :key="i" class="batch-form"><label>{{tr("第")}} {{tr(i+1)}} {{tr("批数量")}}<input v-model="b.qty" type="number" min="1" step="1"/></label><label>{{tr("预计到仓日期")}}<input v-model="b.date" type="date" :min="TODAY"/></label><button v-if="batches.length>1" @click="batches.splice(i,1)" :aria-label="tr(&quot;删除此批次&quot;)"><X :size="16"/></button></div><p class="form-total">{{tr("本次承诺")}} <b>{{tr(fmt(batches.reduce((n,b)=>n+Number(b.qty||0),0)))}}</b> / {{tr(fmt(openQty(selected)))}} {{tr("件")}}</p></template><label class="textarea-label">{{tr(modal==='eta'?'变更原因（必填）':response==='confirm'?'说明 / 剩余数量处理计划':'原因（必填）')}}<textarea v-model="reason" rows="3" :placeholder="tr(&quot;请输入说明，相关人员可在订单历史中追溯。&quot;)"></textarea></label><p v-if="modal==='eta'" class="muted">{{tr("提交后等待内部采购审核，当前交付承诺保持不变。")}}</p></template>
      <template v-else-if="modal==='resolve'"><p class="modal-description">{{tr(activeIssue?.title)}}</p><label class="textarea-label">{{tr("处理状态")}}<select v-model="issueStatus"><option :value="&quot;待处理&quot;">{{tr("待处理")}}</option><option :value="&quot;处理中&quot;">{{tr("处理中")}}</option><option :value="&quot;已解决&quot;">{{tr("已解决")}}</option></select></label><label class="textarea-label">{{tr("处理记录 / 关闭依据")}}<textarea v-model="reason" rows="4" :placeholder="tr(&quot;记录已采取的动作、确认结果和下一步安排。&quot;)"></textarea></label><p class="muted">{{tr("关闭待办不会修改 SAP 数据，也不会消除仍存在的交期风险。")}}</p></template>
      <template v-else-if="modal==='shipment'"><p class="modal-description">{{tr(activeShipment?.id)}} · {{tr(activeShipment?.ref)}}</p><label class="textarea-label">{{tr("运输节点")}}<select v-model="shipmentStage"><option :value="2">{{tr("在途")}}</option><option :value="3">{{tr("已到港")}}</option></select></label><label class="textarea-label">{{tr("当前位置")}}<input v-model="shipmentLocation" :placeholder="tr(&quot;例如：已抵达墨尔本港，待清关&quot;)"/></label><label class="textarea-label">{{tr("运输预计到仓")}}<input type="date" v-model="shipmentEta" :min="TODAY"/></label><p class="muted">{{tr("此操作不更新 SAP 发货、收货数量或供应商原承诺。")}}</p></template>
      <template v-else-if="modal==='reject'"><label class="textarea-label">{{tr("退回原因")}}<textarea v-model="reason" rows="4" :placeholder="tr(&quot;说明需要供应商重新安排的原因。&quot;)"></textarea></label></template>
      <template v-else-if="modal==='reset'"><p class="modal-description">{{tr("清除本次演示中的确认、变更和留言，恢复最初的模拟订单。不会涉及任何真实业务数据。")}}</p></template>
      <template v-else-if="modal==='help'"><div class="help-content"><span class="demo-chip">{{tr("Frappe UI · 交互原型")}}</span><p>{{tr("这是一份使用真实 Frappe UI 组件的前端功能演示，尚未运行 Frappe 后端、接入 SAP 或实施真实账号权限。")}}</p><ol><li>{{tr("切换至")}} <b>{{tr("Longtree · 供应商")}}</b>{{tr("，打开待确认订单，提交数量和交付批次。")}}</li><li>{{tr("对已确认、未发运的订单提交交期变更。")}}</li><li>{{tr("切回")}} <b>{{tr("Regent · 内部采购")}}</b>{{tr("，在“交期与承诺”接受或退回变更。")}}</li><li>{{tr("在“异常与待办”记录处理结果，并查看更新后的报表。")}}</li></ol><p>{{tr("所有数据为虚构样本；操作仅在本次页面会话中有效，刷新即可恢复。")}}</p><a href="https://github.com/frappe/frappe-ui" target="_blank" rel="noreferrer">{{tr("查看 Frappe UI 开源项目 ↗")}}</a></div></template>
      <p v-if="error" class="form-error" role="alert"><CircleAlert :size="16"/>{{tr(error)}}</p>
    </template><template #actions><div class="modal-actions"><Button variant="outline" size="lg" @click="modalOpen=false">{{tr(modal==='help'?'开始体验':'取消')}}</Button><Button v-if="modal!=='help'" variant="solid" class="primary" size="lg" @click="modal==='response'?submitResponse():modal==='eta'?submitEta():modal==='resolve'?saveIssue():modal==='shipment'?saveShipment():modal==='reject'?rejectChange():reset()">{{tr(modal==='reset'?'确认重置':modal==='eta'?'提交变更申请':modal==='response'?'提交响应':'保存记录')}}</Button></div></template></Dialog>
  </div>
</template>
