<script setup>
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { Button, Badge, Dialog } from 'frappe-ui'
import { Boxes, LayoutList, CalendarClock, Ship, ShieldAlert, ChartNoAxesCombined, Database, Search, ArrowUpRight, ArrowRight, ChevronRight, Check, CheckCheck, Clock3, CircleHelp, RefreshCw, Download, Plus, X, LockKeyhole, MessageSquare, PackageCheck, Factory, Plane, CircleAlert, PanelLeftClose } from 'lucide-vue-next'
import { TODAY, fmt, dateLabel, daysLate, openQty, canSee, validateCommitment, seedOrders, seedIssues, seedShipments } from './domain.mjs'
import Overview from './Overview.vue'
import { money } from './analytics.mjs'

const orders=ref(seedOrders()), issues=ref(seedIssues()), shipments=ref(seedShipments())
const page=ref('overview'), role=ref('buyer'), query=ref(''), filter=ref('open'), type=ref('全部类型'), mode=ref('全部运输'), buyer=ref('全部采购员')
const overviewSelection=ref(null)
const selected=ref(null), detailOpen=ref(false), detailTab=ref('overview'), modal=ref(''), modalOpen=ref(false), error=ref(''), notice=ref(''), sidebar=ref(false)
const comment=ref(''), response=ref('confirm'), batches=ref([]), reason=ref(''), issueStatus=ref('处理中'), activeIssue=ref(null), activeShipment=ref(null), shipmentStage=ref(2), shipmentLocation=ref(''), shipmentEta=ref('')
let toastTimer
const nav=[{id:'overview',title:'总览看板',icon:ChartNoAxesCombined},{id:'orders',title:'订单工作台',icon:LayoutList},{id:'delivery',title:'交期与承诺',icon:CalendarClock},{id:'shipments',title:'发运与物流',icon:Ship},{id:'exceptions',title:'异常与待办',icon:ShieldAlert},{id:'reports',title:'履约报表',icon:ChartNoAxesCombined},{id:'data',title:'数据中心',icon:Database}]
const titles={orders:['订单工作台','从订单确认到交付，所有协作在这里发生。'],delivery:['交期与承诺','关注交付变化，保留每一次承诺。'],shipments:['发运与物流','按批次跟进运输，连接订单与到货。'],exceptions:['异常与待办','把风险交给明确的责任人，持续跟进结果。'],reports:['履约报表','基于当前演示订单，实时汇总协作进展。'],data:['数据中心','SAP 持续同步，平台维护协作数据。']}
const visible=computed(()=>orders.value.filter(o=>canSee(o,role.value)))
titles.overview=['总览看板','掌握订单、在途货物与交付风险。']
const visibleIssues=computed(()=>issues.value.filter(i=>visible.value.some(o=>o.id===i.order)))
const activeIssues=computed(()=>visibleIssues.value.filter(i=>i.status!=='已解决'))
const visibleShipments=computed(()=>shipments.value.filter(s=>visible.value.some(o=>o.id===s.order)))
const pending=computed(()=>visible.value.filter(o=>o.pending))
const unconfirmed=computed(()=>visible.value.filter(o=>!o.confirmed))
const openOrders=computed(()=>visible.value.filter(o=>openQty(o)>0))
const stats=computed(()=>[
  {label:'未完成订单',value:new Set(openOrders.value.map(o=>o.po)).size,unit:'张 PO',sub:`${openOrders.value.length} 个订单行`,icon:LayoutList,key:'open'},
  {label:'待供应商确认',value:unconfirmed.value.length,unit:'行',sub:'等待数量与交期承诺',icon:Clock3,key:'unconfirmed'},
  {label:'交期风险',value:visible.value.filter(o=>daysLate(o)>0&&openQty(o)>0).length,unit:'行',sub:'预计到仓晚于需求日期',icon:CalendarClock,key:'risk'},
  {label:'在途数量',value:visible.value.reduce((n,o)=>n+Math.max(0,o.shipped-o.received),0),unit:'件',sub:`${visibleShipments.value.length} 个发运批次`,icon:Ship,key:'transit'},
])
const filtered=computed(()=>visible.value.filter(o=>{
  const match=`${o.po} ${o.part} ${o.name} ${o.supplier}`.toLowerCase().includes(query.value.toLowerCase())
  return match&&(!overviewSelection.value||overviewSelection.value.ids.includes(o.id))&&(type.value==='全部类型'||o.type===type.value)&&(mode.value==='全部运输'||o.mode===mode.value)&&(buyer.value==='全部采购员'||o.buyer===buyer.value)&&
  (filter.value==='all'||(filter.value==='open'&&openQty(o)>0)||(filter.value==='unconfirmed'&&!o.confirmed)||(filter.value==='risk'&&daysLate(o)>0&&openQty(o)>0)||(filter.value==='transit'&&o.shipped>o.received)||(filter.value==='received'&&openQty(o)===0))
}))
const deliveryOrders=computed(()=>visible.value.filter(o=>openQty(o)>0).sort((a,b)=>(Number(!!b.pending)-Number(!!a.pending))||daysLate(b)-daysLate(a)))
const statusTheme=o=>o.pending?'orange':o.status==='待确认'?'orange':o.status==='已收货'?'green':o.status==='在途'||o.status==='部分发运'?'blue':'gray'
const selectedIssues=computed(()=>selected.value?issues.value.filter(i=>i.order===selected.value.id):[])
const selectedShipments=computed(()=>selected.value?shipments.value.filter(s=>s.order===selected.value.id):[])
const modalTitle=computed(()=>({response:'供应商订单响应',eta:'提交交期变更',resolve:'处理异常',shipment:'更新物流进展',reset:'重置演示数据',help:'如何体验这个预览',reject:'退回交期变更'}[modal.value]||'协作操作'))
const reportGroups=computed(()=>['待确认','已确认','生产中','待发运','部分发运','在途','已收货'].map(status=>({status,count:visible.value.filter(o=>o.status===status).length})))
const scopeLabel=computed(()=>role.value==='buyer'?'全部供应商':'Longtree 专属视图')

function toast(text){notice.value=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>notice.value='',4200)}
function navigate(id){if(id==='data'&&role.value!=='buyer')return;page.value=id;sidebar.value=false;detailOpen.value=false}
function inspectOverview(selection){overviewSelection.value=selection;query.value='';type.value='全部类型';mode.value='全部运输';buyer.value='全部采购员';filter.value='all';navigate('orders')}
watch(role,()=>overviewSelection.value=null)
function openOrder(order,tab='overview'){selected.value=order;detailTab.value=tab;detailOpen.value=true;comment.value=''}
function openModal(kind){modal.value=kind;error.value='';reason.value='';modalOpen.value=true}
function startResponse(){response.value='confirm';batches.value=[{qty:openQty(selected.value),date:selected.value.eta||selected.value.required}];openModal('response')}
function startEta(){batches.value=selected.value.batches.map(b=>({...b}));if(!batches.value.length)batches.value=[{qty:openQty(selected.value),date:selected.value.required}];openModal('eta')}
function stamp(){return '09/08 '+new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}
function addEvent(order,text){order.history.unshift({who:role.value==='buyer'?'Regent · 采购':'Longtree · 供应商',time:stamp(),text})}
function submitResponse(){try{
  const order=selected.value
  if(role.value!=='supplier'||!canSee(order,role.value))throw new Error('请切换到 Longtree 供应商视角进行响应。')
  if(order.confirmed)throw new Error('该订单已确认，请使用交期变更。')
  if(response.value!=='confirm'){
    if(!reason.value.trim())throw new Error('请填写原因，便于采购跟进。')
    order.status=response.value==='reject'?'无法供货':'请求调整';
    const existing=issues.value.find(i=>i.order===order.id&&i.category==='供应商响应'&&i.status!=='已解决')
    if(existing){existing.detail=reason.value.trim();existing.title=order.status+' · '+order.name}
    else issues.value.unshift({id:`EX-${issues.value.length+1}`,order:order.id,category:'供应商响应',title:order.status+' · '+order.name,detail:reason.value.trim(),owner:order.buyer,priority:'高',status:'待处理',note:'',due:'2026-09-09'})
    addEvent(order,order.status+'：'+reason.value.trim())
  }else{
    const result=validateCommitment(order,batches.value)
    if(result.partial&&!reason.value.trim())throw new Error('部分确认时，请说明剩余数量的处理计划。')
    order.batches=batches.value.map(b=>({qty:Number(b.qty),date:b.date}));order.eta=result.eta;order.originalEta ||=result.eta;order.confirmed=true;order.status=result.partial?'部分确认':'已确认'
    addEvent(order,`已${result.partial?'部分':''}确认 ${result.total} 件，分 ${order.batches.length} 批交付。${reason.value}`)
    if(result.partial) issues.value.unshift({id:`EX-${issues.value.length+1}`,order:order.id,category:'部分确认',title:`剩余 ${openQty(order)-result.total} 件待承诺`,detail:reason.value,owner:order.buyer,priority:'中',status:'待处理',note:'',due:'2026-09-10'})
  }
  modalOpen.value=false;detailTab.value='commitment';toast('响应已记录，采购视角已同步更新。')
}catch(e){error.value=e.message}}
function submitEta(){try{
  const o=selected.value
  if(!o.confirmed||o.shipped>0)throw new Error('仅支持对已确认且未发运订单提交变更。')
  if(o.pending)throw new Error('已有一项交期变更等待采购审核。')
  if(!reason.value.trim())throw new Error('请填写交期变更原因。')
  const result=validateCommitment(o,batches.value)
  o.pending={batches:batches.value.map(b=>({qty:Number(b.qty),date:b.date})),eta:result.eta,reason:reason.value.trim(),who:role.value==='supplier'?'Longtree':'Regent 代录'}
  addEvent(o,`提出交期变更：${o.eta} → ${result.eta}。原因：${reason.value}`);modalOpen.value=false;toast('变更已提交；采购接受前，原承诺保持有效。')
}catch(e){error.value=e.message}}
function approve(o){if(role.value!=='buyer'||!o.pending)return;const p=o.pending;o.eta=p.eta;o.batches=p.batches;o.pending=null;addEvent(o,`采购接受交期变更，新预计到仓日期 ${o.eta}`);toast('已接受变更，交期视图和报表已更新。')}
function rejectChange(){if(!reason.value.trim()){error.value='请填写退回原因。';return}if(role.value!=='buyer'||!selected.value?.pending)return;addEvent(selected.value,'采购退回交期变更：'+reason.value);selected.value.pending=null;modalOpen.value=false;toast('已退回变更，保留原交付承诺。')}
function sendComment(){if(!comment.value.trim())return;selected.value.comments.unshift({who:role.value==='buyer'?'Regent · 采购':'Longtree · 供应商',time:stamp(),text:comment.value.trim()});addEvent(selected.value,'添加了订单沟通记录');comment.value='';toast('留言已加入订单记录。')}
function startIssue(i){activeIssue.value=i;issueStatus.value=i.status==='已解决'?'处理中':i.status;openModal('resolve');reason.value=i.note||''}
function saveIssue(){if(role.value!=='buyer')return;if(!reason.value.trim()){error.value='请填写处理记录或关闭依据。';return}activeIssue.value.status=issueStatus.value;activeIssue.value.note=reason.value.trim();addEvent(orders.value.find(o=>o.id===activeIssue.value.order),`${activeIssue.value.id} ${issueStatus.value}：${reason.value}`);modalOpen.value=false;toast('处理记录已更新。订单事实与交期风险按实际数据计算。')}
function startShipment(s){activeShipment.value=s;shipmentStage.value=s.stage;shipmentLocation.value=s.location;shipmentEta.value=s.eta;openModal('shipment')}
function saveShipment(){if(!shipmentLocation.value.trim()||!shipmentEta.value){error.value='请补充当前位置与预计到仓日期。';return}if(shipmentEta.value<TODAY){error.value='预计到仓日期不能早于演示业务日期。';return}Object.assign(activeShipment.value,{stage:Number(shipmentStage.value),location:shipmentLocation.value.trim(),eta:shipmentEta.value,updated:stamp()});addEvent(orders.value.find(o=>o.id===activeShipment.value.order),'更新物流节点：'+shipmentLocation.value+'；运输预计到仓 '+shipmentEta.value);modalOpen.value=false;toast('物流进展已更新；正式发货与收货记录仍以 SAP 为准。')}
function exportOrders(){const quote=s=>'"'+String(s).replaceAll('"','""')+'"';const csv='\uFEFF'+[['PO','订单行','物料编码','供应商','订购数量','已收数量','未交数量','需求日期','承诺到仓','状态'],...filtered.value.map(o=>[o.po,o.item,o.part,o.supplier,o.qty,o.received,openQty(o),o.required,o.eta,o.status])].map(r=>r.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Regent-演示订单.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('已导出当前筛选范围的演示订单。')}
function reset(){overviewSelection.value=null;orders.value=seedOrders();issues.value=seedIssues();shipments.value=seedShipments();selected.value=null;detailOpen.value=false;modalOpen.value=false;query.value='';filter.value='open';toast('演示已恢复初始状态。')}
watch(role,()=>{selected.value=null;detailOpen.value=false;modalOpen.value=false;buyer.value='全部采购员';if(page.value==='data')page.value='orders';toast(role.value==='supplier'?'已切换：Longtree 供应商，只展示本供应商的模拟订单。':'已切换：Regent 内部采购，可审核变更和处理异常。')})
onUnmounted(()=>clearTimeout(toastTimer))
const toolLifecycle=new AbortController()
onMounted(()=>{
  const context=document.modelContext
  if(!context?.registerTool)return
  const tools=[
    {name:'read_demo_orders',description:'Read the fictional orders visible to the current demo role.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>visible.value.map(o=>({id:o.id,po:o.po,part:o.part,status:o.status,eta:o.eta,openQty:openQty(o)}))},
    {name:'open_demo_order',description:'Open an order detail in the current demo role. Does not modify the order.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||typeof input.id!=='string')throw new Error('An order id is required');const order=visible.value.find(o=>o.id===input.id);if(!order)throw new Error('Order not available in current demo scope');openOrder(order);await nextTick();return {opened:order.id}}},
  ]
  for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:toolLifecycle.signal})).catch(()=>{})}catch{}}
})
onUnmounted(()=>toolLifecycle.abort())
</script>

<template>
  <div class="workspace">
    <aside class="sidebar" :class="{mobileOpen:sidebar}">
      <a class="brand" href="#/" @click.prevent="navigate('overview')"><span class="brandmark"><Boxes :size="23"/></span><span>REGENT<small>SUPPLIER COLLABORATION</small></span></a>
      <div class="workspace-label">采购与供应商协作 <span>AU / CN</span></div>
      <nav aria-label="主要导航"><button v-for="n in nav.filter(n=>role==='buyer'||n.id!=='data')" :key="n.id" :class="['navitem',{active:page===n.id}]" @click="navigate(n.id)"><component :is="n.icon" :size="19"/><span>{{n.title}}</span><span v-if="n.id==='exceptions'&&activeIssues.length" class="navcount">{{activeIssues.length}}</span></button></nav>
      <div class="sidebar-bottom"><div class="connection"><span class="live-dot"></span><div>SAP + 协作平台<small>演示环境 · 业务日期 09/08</small></div></div><button class="help-link" @click="openModal('help')"><CircleHelp :size="17"/> 预览说明 <ArrowUpRight :size="15"/></button><a href="https://github.com/frappe/frappe-ui" target="_blank" rel="noreferrer" class="powered">Built with Frappe UI ↗</a></div>
    </aside>
    <div class="main-shell">
      <header class="topbar"><div class="crumb"><button class="mobile-menu" aria-label="展开导航" @click="sidebar=!sidebar"><PanelLeftClose :size="20"/></button><span>供应商协作</span><ChevronRight :size="14"/><strong>{{titles[page][0]}}</strong></div><div class="topbar-right"><span class="demo-chip">功能预览 · 模拟数据</span><label class="role-select"><span class="avatar">{{role==='buyer'?'R':'L'}}</span><select v-model="role" aria-label="切换演示角色"><option value="buyer">Regent · 内部采购</option><option value="supplier">Longtree · 供应商</option></select></label></div></header>
      <main>
        <div class="page-heading"><div><div class="eyebrow">{{scopeLabel}}<span> / </span> ORDER COLLABORATION</div><h1>{{titles[page][0]}}</h1><p>{{titles[page][1]}}</p></div><div class="heading-actions"><Button variant="outline" size="lg" @click="openModal('reset')"><template #prefix><RefreshCw :size="15"/></template>重置演示</Button><Button v-if="page==='orders'" variant="solid" class="primary" size="lg" @click="exportOrders"><template #prefix><Download :size="15"/></template>导出当前视图</Button></div></div>

        <Overview v-if="page==='overview'" :orders="visible" :shipments="visibleShipments" :issues="visibleIssues" :role="role" @inspect="inspectOverview" @open-order="openOrder" @navigate="navigate"/>
        <template v-else-if="page==='orders'">
          <div v-if="overviewSelection" class="overview-selection"><span>来自总览：<strong>{{overviewSelection.label}}</strong> · {{overviewSelection.ids.length}} 行</span><Button variant="ghost" @click="overviewSelection=null">清除看板范围 <X :size="14"/></Button><Button variant="outline" @click="navigate('overview')">返回总览</Button></div>
          <div class="metric-grid"><button v-for="s in stats" :key="s.key" :class="['metric',{chosen:filter===s.key}]" @click="filter=s.key"><div class="metric-label">{{s.label}}<component :is="s.icon" :size="18"/></div><div class="metric-number">{{fmt(s.value)}}<span>{{s.unit}}</span></div><div class="metric-foot">{{s.sub}}<ArrowUpRight :size="15"/></div></button></div>
          <div v-if="activeIssues.length||pending.length" class="attention"><span class="attention-icon"><CircleAlert :size="19"/></span><div><strong>{{pending.length?`${pending.length} 项交期变更等待审核`:`${activeIssues.length} 项协作事项需要跟进`}}</strong><span>{{pending.length?'供应商提出了新的交付安排，原承诺在审核前继续有效。':'优先关注交期延误、物料编码与待订舱订单。'}}</span></div><button @click="navigate(pending.length?'delivery':'exceptions')">查看待办 <ArrowRight :size="16"/></button></div>
          <section class="panel order-panel"><div class="tabs"><button v-for="t in [['open','未完成订单'],['unconfirmed','待确认'],['risk','交期风险'],['transit','在途'],['received','已收货'],['all','全部订单']]" :key="t[0]" :class="{selected:filter===t[0]}" @click="filter=t[0]">{{t[1]}}<span v-if="t[0]==='unconfirmed'">{{unconfirmed.length}}</span></button></div>
            <div class="filters"><label class="searchbox"><Search :size="17"/><input v-model="query" placeholder="搜索 PO、物料编码或名称…" aria-label="搜索订单"/><button v-if="query" @click="query=''" aria-label="清空搜索"><X :size="15"/></button></label><select v-model="type" aria-label="订单类型"><option>全部类型</option><option>生产订单</option><option>售后配件</option></select><select v-model="mode" aria-label="运输方式"><option>全部运输</option><option>海运</option><option>空运</option></select><select v-if="role==='buyer'" v-model="buyer" aria-label="采购员"><option>全部采购员</option><option>Karen A.</option><option>Nishi A.</option></select><span class="result-count">{{filtered.length}} 个订单行</span></div>
            <div class="table-scroll"><table class="orders-table"><thead><tr><th>订单 / 物料</th><th>供应商 / 类型</th><th class="right">订购 / 未交</th><th>需求 / 承诺到仓</th><th>履约进展</th><th>协作状态</th><th></th></tr></thead><tbody><tr v-for="o in filtered" :key="o.id" @click="openOrder(o)"><td><button class="order-link" @click.stop="openOrder(o)">{{o.po}}<span>/ {{o.item}}</span></button><div class="material-name">{{o.name}}</div><small class="mono muted">{{o.part}}</small></td><td><strong class="supplier-name">{{o.supplier}}</strong><small>{{o.type}} · {{o.buyer}}</small></td><td class="right"><strong>{{fmt(o.qty)}}</strong><small><span :class="{'teal-text':openQty(o)>0}">{{fmt(openQty(o))}} 未交</span></small></td><td><span class="date-pair">{{dateLabel(o.required)}}<ArrowRight :size="12"/><strong :class="{'danger-text':daysLate(o)>0}">{{dateLabel(o.eta)}}</strong></span><small v-if="daysLate(o)>0" class="danger-text">晚于需求 {{daysLate(o)}} 天</small><small v-else-if="o.eta">{{o.mode}} · {{o.received===o.qty?'已完成':'交期正常'}}</small><small v-else>待供应商承诺</small></td><td><div class="progress-text"><span>{{o.progress===100?'生产完成':o.progress?`生产 ${o.progress}%`:'尚未开始'}}</span><span>{{o.progress}}%</span></div><div class="progress-track"><i :style="{width:o.progress+'%'}"></i></div></td><td><Badge :theme="statusTheme(o)" size="lg">{{o.pending?'变更待审核':o.status}}</Badge></td><td><button class="row-arrow" aria-label="查看订单详情" @click.stop="openOrder(o)"><ChevronRight :size="18"/></button></td></tr><tr v-if="!filtered.length"><td colspan="7" class="empty"><Search :size="28"/><strong>没有匹配的订单</strong><span>试试其他关键词或筛选条件。</span><Button variant="outline" @click="overviewSelection=null;query='';type='全部类型';mode='全部运输';buyer='全部采购员';filter='all'">清除筛选</Button></td></tr></tbody></table></div><footer class="table-footer"><span>按 PO 订单行展示 · 数量单位：件</span><span>全部 {{filtered.length}} 行 <span class="page-box">1</span></span></footer>
          </section>
          <div class="source-note"><LockKeyhole :size="14"/> SAP 订单数据只读；确认、承诺与沟通在平台维护。<span>本次演示操作在刷新后重置。</span></div>
        </template>

        <template v-else-if="page==='delivery'">
          <div class="section-summary"><span><strong>{{pending.length}}</strong> 项变更待审核</span><span><strong>{{visible.filter(o=>daysLate(o)>0&&openQty(o)>0).length}}</strong> 行存在交期风险</span><span>日期统一表示 <b>预计到仓</b></span></div>
          <section class="panel"><div class="panel-heading"><h2>交付承诺</h2><span class="muted">需求 → 当前承诺 → 变更申请</span></div><div v-for="o in deliveryOrders" :key="o.id" class="delivery-row"><div><button class="order-link" @click="openOrder(o,'commitment')">{{o.po}} <span>/ {{o.item}}</span></button><p>{{o.name}}</p><small>{{o.supplier}} · {{o.buyer}}</small></div><div class="date-block"><small>SAP 需求到仓</small><strong>{{dateLabel(o.required)}}</strong></div><ArrowRight class="muted" :size="17"/><div class="date-block"><small>当前承诺到仓</small><strong :class="{'danger-text':daysLate(o)>0}">{{dateLabel(o.eta)}}</strong></div><div class="delivery-status"><Badge v-if="o.pending" theme="orange" size="lg">申请 {{dateLabel(o.pending.eta)}}</Badge><Badge v-else-if="daysLate(o)>0" theme="red" size="lg">延后 {{daysLate(o)}} 天</Badge><Badge v-else :theme="o.eta?'green':'gray'" size="lg">{{o.eta?'按计划':'待确认'}}</Badge></div><Button variant="outline" @click="openOrder(o,'commitment')">{{o.pending&&role==='buyer'?'审核变更':'查看安排'}}</Button></div></section>
        </template>

        <template v-else-if="page==='shipments'">
          <div class="shipment-grid"><section v-for="s in visibleShipments" :key="s.id" class="panel shipment-card"><div class="shipment-top"><span class="transport-icon"><component :is="s.mode==='海运'?Ship:Plane" :size="24"/></span><div><h2>{{s.id}}</h2><small>{{s.mode}} · {{s.ref}}</small></div><Badge theme="blue" size="lg">{{['待出发','已离港','在途','已到港'][s.stage]}}</Badge></div><div class="route-line"><div><small>起运地</small><h3>{{s.from}}</h3><span>{{dateLabel(s.etd)}} 出发</span></div><div class="route-rule"><component :is="s.mode==='海运'?Ship:Plane" :size="20"/></div><div class="right"><small>目的地</small><h3>{{s.to}}</h3><span>{{dateLabel(s.eta)}} 预计到仓</span></div></div><div class="milestones"><div v-for="(label,i) in ['待出发','已离港','在途','已到港']" :class="{done:i<=s.stage}" :key="label"><span><Check v-if="i<s.stage" :size="12"/><i v-else></i></span>{{label}}</div></div><div class="shipment-info"><span>当前位置<strong>{{s.location}}</strong></span><span>承运信息<strong>{{s.carrier}}</strong></span><span>发运数量<strong>{{fmt(s.qty)}} 件</strong></span></div><footer><small>模拟更新 {{s.updated}}</small><Button variant="outline" @click="startShipment(s)">更新物流</Button></footer><button class="shipment-order" @click="openOrder(orders.find(o=>o.id===s.order),'logistics')">关联 PO {{s.order.replace('-',' / ')}} <ArrowUpRight :size="14"/></button></section></div><div class="info-box"><LockKeyhole :size="19"/><p>平台维护运输节点及运输预计到仓时间。正式发货和收货数量由 SAP 同步；物流到港不等于 SAP 已收货。</p></div>
        </template>

        <template v-else-if="page==='exceptions'">
          <div class="section-summary"><span><strong>{{activeIssues.length}}</strong> 项待跟进</span><span><strong>{{visibleIssues.filter(i=>i.status==='已解决').length}}</strong> 项已解决</span><span>每项异常都有责任人与处理记录</span></div><section class="panel"><article v-for="i in visibleIssues" :key="i.id" class="issue-card"><div class="issue-icon" :class="{resolved:i.status==='已解决'}"><CheckCheck v-if="i.status==='已解决'" :size="21"/><ShieldAlert v-else :size="21"/></div><div class="issue-main"><div class="issue-title"><h2>{{i.title}}</h2><Badge :theme="i.status==='已解决'?'green':i.priority==='高'?'red':'orange'">{{i.status==='已解决'?'已解决':i.priority+'优先级'}}</Badge></div><p>{{i.detail}}</p><div class="issue-meta"><button @click="openOrder(orders.find(o=>o.id===i.order))">{{i.order.replace('-',' / ')}}</button><span>{{i.category}}</span><span>负责人 {{i.owner}}</span><span>跟进截止 {{dateLabel(i.due)}}</span></div><div v-if="i.note" class="issue-note">处理记录：{{i.note}}</div></div><div class="issue-action"><Badge theme="gray">{{i.status}}</Badge><Button v-if="role==='buyer'" variant="outline" @click="startIssue(i)">{{i.status==='已解决'?'重新跟进':'处理异常'}}</Button><Button v-else variant="outline" @click="openOrder(orders.find(o=>o.id===i.order),'activity')">补充说明</Button></div></article></section>
        </template>

        <template v-else-if="page==='reports'">
          <div class="report-note"><ChartNoAxesCombined :size="19"/> 当前范围：{{scopeLabel}} · 全部 {{visible.length}} 个订单行 · 统计随演示操作更新</div><div class="report-grid"><section class="panel report-panel"><h2>订单履约分布</h2><p>按订单行统计</p><div v-for="g in reportGroups" :key="g.status" class="bar-row"><span>{{g.status}}</span><div><i :style="{width:(g.count/Math.max(...reportGroups.map(r=>r.count),1))*100+'%'}"></i></div><strong>{{g.count}}</strong></div></section><section class="panel report-panel"><h2>供应商确认</h2><p>至少已确认部分数量的订单行占比</p><div class="report-big">{{Math.round(visible.filter(o=>o.confirmed).length/visible.length*100)}}<span>%</span></div><div class="wide-progress"><i :style="{width:(visible.filter(o=>o.confirmed).length/visible.length*100)+'%'}"></i></div><div class="report-detail"><span>已确认 {{visible.filter(o=>o.confirmed).length}} 行</span><span>待确认 {{unconfirmed.length}} 行</span></div><Button variant="outline" @click="page='orders';filter='unconfirmed'">查看待确认订单 <ArrowRight :size="14"/></Button></section></div><section class="panel report-panel"><h2>数量核对</h2><div class="quantity-grid"><div><small>订购总量</small><strong>{{fmt(visible.reduce((n,o)=>n+o.qty,0))}}<span>件</span></strong></div><div><small>已收货 · SAP</small><strong>{{fmt(visible.reduce((n,o)=>n+o.received,0))}}<span>件</span></strong></div><div><small>在途 · 已发未收</small><strong>{{fmt(stats[3].value)}}<span>件</span></strong></div><div><small>尚未发运</small><strong>{{fmt(visible.reduce((n,o)=>n+o.qty-o.shipped,0))}}<span>件</span></strong></div></div><p class="muted">本演示物料统一为“件”；正式系统需按计量单位分组。准时交付率需真实收货历史后再计算。</p></section>
        </template>

        <template v-else-if="page==='data'&&role==='buyer'">
          <div class="data-flow"><div><Database :size="25"/><strong>SAP</strong><small>正式订单 / 发货 / 收货</small></div><ArrowRight :size="22"/><div class="central"><Boxes :size="26"/><strong>协作平台</strong><small>确认 / 交期 / 沟通 / 异常</small></div><ArrowRight :size="22"/><div><ChartNoAxesCombined :size="25"/><strong>可信报表</strong><small>统一口径 / 数据可追溯</small></div></div><section class="panel"><div class="panel-heading"><h2>数据运行状态</h2><Badge theme="green" size="lg">模拟状态</Badge></div><div class="data-row"><div><strong>SAP 订单同步</strong><small>计划持续同步正式业务记录</small></div><span>{{orders.length}} 个演示订单行</span><Badge theme="green">示例已载入</Badge></div><div class="data-row"><div><strong>待处理的数据问题</strong><small>在平台分派、核对和记录修正结果</small></div><span>{{issues.filter(i=>i.category==='数据问题'&&i.status!=='已解决').length}} 项</span><Button variant="outline" @click="navigate('exceptions')">查看问题</Button></div><div class="data-row"><div><strong>平台协作记录</strong><small>供应商确认、交期变更和沟通</small></div><span>{{orders.reduce((n,o)=>n+o.history.length,0)}} 条事件</span><Badge theme="green">本次会话内更新</Badge></div></section><section class="panel migration-panel"><div class="migration-check"><CheckCheck :size="22"/></div><div><h2>初始迁移已完成 <Badge theme="gray">演示场景</Badge></h2><p>历史 Excel 仅用于初次导入和核对。切换后，日常业务由 SAP 与平台维护。</p><div class="migration-steps"><span>01 导入历史数据</span><ChevronRight :size="15"/><span>02 核对与业务确认</span><ChevronRight :size="15"/><strong>03 切换平台协作 ✓</strong></div><small>尚未接入实际文件或 SAP；这里展示未来正式运行后的界面。</small></div></section>
        </template>
      </main>
    </div>
    <div v-if="notice" class="toast" role="status"><Check :size="18"/>{{notice}}<button @click="notice=''" aria-label="关闭提示"><X :size="15"/></button></div>

    <Dialog v-model="detailOpen" :options="{title:'订单详情',size:'3xl'}"><template #body-content><div v-if="selected" class="order-detail"><div class="detail-title"><div><div class="eyebrow">PURCHASE ORDER / {{selected.item}}</div><h2>{{selected.po}}</h2><p>{{selected.name}}</p><small>{{selected.part}} · {{selected.supplier}}</small></div><Badge :theme="statusTheme(selected)" size="lg">{{selected.pending?'变更待审核':selected.status}}</Badge></div><div class="detail-tabs"><button v-for="t in [['overview','订单概览'],['commitment','交付承诺'],['logistics','发运记录'],['activity','沟通与历史']]" :key="t[0]" :class="{active:detailTab===t[0]}" @click="detailTab=t[0]">{{t[1]}}</button></div>
      <div v-if="detailTab==='overview'" class="overview-price"><span>示例单价 / AUD<strong>{{money(selected.unitPrice)}}<small> / 件</small></strong></span><span>未交货值 / AUD<strong>{{money(openQty(selected)*selected.unitPrice)}}</strong></span><small>模拟采购价格 · 不含税费与运费</small></div>
      <template v-if="detailTab==='overview'"><div class="read-only-label"><LockKeyhole :size="14"/> SAP 数据 · 只读</div><div class="detail-fields"><div><small>物料描述</small><strong>{{selected.en}}</strong></div><div><small>采购员 / 工厂</small><strong>{{selected.buyer}} / {{selected.plant}}</strong></div><div><small>订购数量</small><strong>{{fmt(selected.qty)}} 件</strong></div><div><small>已收货 / 未交</small><strong>{{fmt(selected.received)}} / {{fmt(openQty(selected))}} 件</strong></div><div><small>订单类型</small><strong>{{selected.type}}</strong></div><div><small>需求到仓日期</small><strong>{{selected.required}}</strong></div></div><div class="detail-subheading"><h3>履约进展</h3><span>供应商反馈</span></div><div class="production-progress"><Factory :size="21"/><div><strong>{{selected.progress===100?'生产已完成':selected.progress?'正在生产':'尚未开始生产'}}</strong><div class="progress-track"><i :style="{width:selected.progress+'%'}"></i></div></div><b>{{selected.progress}}%</b></div><div v-for="i in selectedIssues.filter(i=>i.status!=='已解决')" :key="i.id" class="detail-alert"><CircleAlert :size="18"/><div><strong>{{i.title}}</strong><p>{{i.detail}}</p></div></div><div class="detail-bottom-action"><p>{{role==='buyer'?'供应商响应可在右上角切换到供应商视角体验。':'请确认数量和预计到仓日期，或说明无法供货的原因。'}}</p><Button v-if="role==='supplier'&&!selected.confirmed" variant="solid" class="primary" size="lg" @click="startResponse">响应订单</Button><Button v-else variant="solid" class="primary" size="lg" @click="detailTab='commitment'">查看交付承诺</Button></div></template>
      <template v-if="detailTab==='commitment'"><div class="commitment-dates"><div><small>需求到仓 · SAP</small><strong>{{dateLabel(selected.required)}}</strong></div><ArrowRight :size="18"/><div><small>当前承诺 · 平台</small><strong :class="{'danger-text':daysLate(selected)>0}">{{dateLabel(selected.eta)}}</strong></div></div><div v-if="selected.pending" class="pending-change"><div><Badge theme="orange">变更待审核</Badge><strong>申请到仓 {{selected.pending.eta}}</strong><p>{{selected.pending.reason}}</p><small>{{selected.pending.who}} 提出 · 当前承诺在审核前不变</small></div><div v-if="role==='buyer'" class="button-row"><Button variant="outline" @click="openModal('reject')">退回</Button><Button variant="solid" class="primary" @click="approve(selected)">接受变更</Button></div></div><div class="detail-subheading"><h3>分批交付安排</h3><span>已承诺 {{fmt(selected.batches.reduce((n,b)=>n+b.qty,0))}} 件</span></div><div v-if="!selected.batches.length" class="mini-empty"><CalendarClock :size="27"/><p>供应商尚未提交交付承诺</p></div><div v-for="(b,index) in selected.batches" :key="index" class="batch-row"><span class="batch-number">{{String(index+1).padStart(2,'0')}}</span><div><small>交付数量</small><strong>{{fmt(b.qty)}} 件</strong></div><div><small>预计到仓</small><strong>{{b.date}}</strong></div><Badge theme="gray">{{selected.mode}}</Badge></div><p class="muted detail-hint">交付批次表示数量与到仓承诺；实际发运记录单独跟踪。</p><div class="button-row"><Button v-if="role==='supplier'&&!selected.confirmed" variant="solid" class="primary" size="lg" @click="startResponse">响应订单 / 分批确认</Button><Button v-if="selected.confirmed&&!selected.shipped&&!selected.pending" variant="solid" class="primary" size="lg" @click="startEta">提交交期变更</Button></div><p v-if="selected.shipped>0" class="info-box">该订单已有发运，运输时间请在发运记录中跟进。</p></template>
      <template v-if="detailTab==='logistics'"><div v-if="!selectedShipments.length" class="mini-empty"><Ship :size="32"/><h3>暂无发运记录</h3><p>供应商反馈生产进展；正式发货记录由 SAP 同步。</p></div><div v-for="s in selectedShipments" :key="s.id" class="detail-shipment"><div class="detail-subheading"><h3>{{s.id}}</h3><Badge theme="blue">{{s.mode}}</Badge></div><div class="detail-fields"><div><small>集装箱 / 运单号</small><strong>{{s.ref}}</strong></div><div><small>发运数量</small><strong>{{s.qty}} 件</strong></div><div><small>当前位置</small><strong>{{s.location}}</strong></div><div><small>运输预计到仓</small><strong>{{s.eta}}</strong></div></div><Button variant="outline" @click="startShipment(s)">更新物流进展</Button></div></template>
      <template v-if="detailTab==='activity'"><div class="comment-compose"><label for="order-comment">订单沟通</label><textarea id="order-comment" v-model="comment" rows="3" placeholder="补充交期原因、跟进进展或供应商说明…"></textarea><div><small>{{role==='buyer'?'以 Regent 采购身份留言':'以 Longtree 供应商身份留言'}}</small><Button variant="solid" class="primary" :disabled="!comment.trim()" @click="sendComment">发送留言</Button></div></div><div v-for="(c,i) in selected.comments" :key="i" class="comment"><span class="comment-avatar"><MessageSquare :size="16"/></span><div><strong>{{c.who}}</strong><small>{{c.time}}</small><p>{{c.text}}</p></div></div><h3 class="history-heading">操作历史</h3><div class="timeline"><div v-for="(e,i) in [...selected.history].sort((a,b)=>b.time.localeCompare(a.time))" :key="i"><i></i><small>{{e.time}} · {{e.who}}</small><p>{{e.text}}</p></div></div></template>
    </div></template></Dialog>

    <Dialog v-model="modalOpen" :options="{title:modalTitle,size:modal==='help'?'xl':'lg'}"><template #body-content>
      <template v-if="modal==='response'||modal==='eta'"><div class="modal-context">{{selected?.po}} / {{selected?.item}}<strong>{{selected?.name}}</strong><span>未交 {{fmt(openQty(selected))}} 件 · 需求到仓 {{selected?.required}}</span></div><div v-if="modal==='response'" class="response-options"><button v-for="r in [['confirm','确认供货'],['change','请求调整'],['reject','无法供货']]" :key="r[0]" :class="{active:response===r[0]}" @click="response=r[0]">{{r[1]}}</button></div><template v-if="modal==='eta'||response==='confirm'"><div class="form-heading"><strong>{{modal==='eta'?'新的交付安排':'交付安排'}}</strong><Button variant="ghost" @click="batches.push({qty:1,date:selected.required})"><template #prefix><Plus :size="14"/></template>添加批次</Button></div><div v-for="(b,i) in batches" :key="i" class="batch-form"><label>第 {{i+1}} 批数量<input v-model="b.qty" type="number" min="1" step="1"/></label><label>预计到仓日期<input v-model="b.date" type="date" :min="TODAY"/></label><button v-if="batches.length>1" @click="batches.splice(i,1)" aria-label="删除此批次"><X :size="16"/></button></div><p class="form-total">本次承诺 <b>{{fmt(batches.reduce((n,b)=>n+Number(b.qty||0),0))}}</b> / {{fmt(openQty(selected))}} 件</p></template><label class="textarea-label">{{modal==='eta'?'变更原因（必填）':response==='confirm'?'说明 / 剩余数量处理计划':'原因（必填）'}}<textarea v-model="reason" rows="3" placeholder="请输入说明，相关人员可在订单历史中追溯。"></textarea></label><p v-if="modal==='eta'" class="muted">提交后等待内部采购审核，当前交付承诺保持不变。</p></template>
      <template v-else-if="modal==='resolve'"><p class="modal-description">{{activeIssue?.title}}</p><label class="textarea-label">处理状态<select v-model="issueStatus"><option>待处理</option><option>处理中</option><option>已解决</option></select></label><label class="textarea-label">处理记录 / 关闭依据<textarea v-model="reason" rows="4" placeholder="记录已采取的动作、确认结果和下一步安排。"></textarea></label><p class="muted">关闭待办不会修改 SAP 数据，也不会消除仍存在的交期风险。</p></template>
      <template v-else-if="modal==='shipment'"><p class="modal-description">{{activeShipment?.id}} · {{activeShipment?.ref}}</p><label class="textarea-label">运输节点<select v-model="shipmentStage"><option :value="2">在途</option><option :value="3">已到港</option></select></label><label class="textarea-label">当前位置<input v-model="shipmentLocation" placeholder="例如：已抵达墨尔本港，待清关"/></label><label class="textarea-label">运输预计到仓<input type="date" v-model="shipmentEta" :min="TODAY"/></label><p class="muted">此操作不更新 SAP 发货、收货数量或供应商原承诺。</p></template>
      <template v-else-if="modal==='reject'"><label class="textarea-label">退回原因<textarea v-model="reason" rows="4" placeholder="说明需要供应商重新安排的原因。"></textarea></label></template>
      <template v-else-if="modal==='reset'"><p class="modal-description">清除本次演示中的确认、变更和留言，恢复最初的模拟订单。不会涉及任何真实业务数据。</p></template>
      <template v-else-if="modal==='help'"><div class="help-content"><span class="demo-chip">Frappe UI · 交互原型</span><p>这是一份使用真实 Frappe UI 组件的前端功能演示，尚未运行 Frappe 后端、接入 SAP 或实施真实账号权限。</p><ol><li>切换至 <b>Longtree · 供应商</b>，打开待确认订单，提交数量和交付批次。</li><li>对已确认、未发运的订单提交交期变更。</li><li>切回 <b>Regent · 内部采购</b>，在“交期与承诺”接受或退回变更。</li><li>在“异常与待办”记录处理结果，并查看更新后的报表。</li></ol><p>所有数据为虚构样本；操作仅在本次页面会话中有效，刷新即可恢复。</p><a href="https://github.com/frappe/frappe-ui" target="_blank" rel="noreferrer">查看 Frappe UI 开源项目 ↗</a></div></template>
      <p v-if="error" class="form-error" role="alert"><CircleAlert :size="16"/>{{error}}</p>
    </template><template #actions><div class="modal-actions"><Button variant="outline" size="lg" @click="modalOpen=false">{{modal==='help'?'开始体验':'取消'}}</Button><Button v-if="modal!=='help'" variant="solid" class="primary" size="lg" @click="modal==='response'?submitResponse():modal==='eta'?submitEta():modal==='resolve'?saveIssue():modal==='shipment'?saveShipment():modal==='reject'?rejectChange():reset()">{{modal==='reset'?'确认重置':modal==='eta'?'提交变更申请':modal==='response'?'提交响应':'保存记录'}}</Button></div></template></Dialog>
  </div>
</template>
