<script setup>
import { ref } from 'vue'
import { t } from './i18n.mjs'
import { label } from './reconciliation.mjs'
defineProps({configured:Boolean,connected:Boolean,busy:Boolean,status:String,error:String,email:String,revision:Number,savedAt:[String,Number],deleted:Array,publicTest:Boolean,summary:Object})
const emit=defineEmits(['connect','disconnect','restore'])
const emailInput=ref(''),password=ref('')
const l=(zh,en)=>t(label(zh,en))
function login(){emit('connect',{email:emailInput.value,password:password.value});password.value=''}
</script>
<template><section class="cloud-panel ops">
  <div class="cloud-title"><div><h2>{{l('数据保存与同步','Data saving & synchronization')}}</h2><p>{{l('SAP 原始数据与平台协作记录分别保存','SAP source data and platform collaboration are stored separately')}}</p></div><span class="demo-chip">{{connected?'Firebase':l('未连接云端','Cloud disconnected')}}</span></div>
  <div class="cloud-status-grid"><div><small>{{l('网页操作','Web operations')}}</small><strong>{{status}}</strong><span v-if="savedAt">{{l('上次保存','Last saved')}} · {{new Date(savedAt).toLocaleString()}}</span></div><div><small>{{l('SAP 定时同步','Scheduled SAP sync')}}</small><strong>{{l('待启用内网同步程序','Internal sync agent not enabled')}}</strong><span>{{l('SAP 保持只读；当前不是实时 SAP 快照','SAP remains read-only; this is not a live SAP snapshot')}}</span></div></div>
  <p v-if="publicTest" class="ops-note">{{l('公开测试：无需登录，持有数据库地址的人可读写。页面操作会保存修改版本；操作人未经过身份验证。','Public test: no sign-in; database access is public. Changes retain revisions, but actors are not authenticated.')}}</p>
  <div v-if="summary" class="cloud-status-grid"><div><small>{{l('主台账记录','Master records')}}</small><strong>{{summary.masterRecords}} · {{summary.masterCompletion.NG}} {{l('条未完成标记','marked open')}}</strong><span>{{summary.masterCompletion.OK}} OK · {{summary.masterCompletion['澳洲取消订单']}} {{l('取消','cancelled')}}</span></div><div><small>{{l('辅助表关联','Supplement links')}}</small><strong>{{summary.linkedSupplementRows}} {{l('条已关联，不重复计单','linked; no duplicate orders')}}</strong><span>{{summary.reviewTasks}} {{l('条初始化核对项（含历史），明细见订单来源','initial review items including history; see order source details')}}</span></div></div>
  <details v-if="summary?.sourceRows" class="ops-definitions" open><summary>{{l('四份来源表的导入范围','Coverage of the four source workbooks')}}</summary><table><thead><tr><th>{{l('来源','Source')}}</th><th>{{l('业务记录数','Business records')}}</th><th>{{l('用途','Use')}}</th></tr></thead><tbody><tr v-for="f in [['master','年度订单主台账','Annual order master','主记录，含已完成和取消','Master records, including completed and cancelled'],['open','未完成清单','Open order list','补充主台账，不重复计单','Enriches master records; no duplicate orders'],['weekly','每周发运表','Weekly dispatch list','保留本周报发依据','Retains weekly dispatch evidence'],['delayed','延迟发运表','Delayed dispatch list','补充延期跟进信息','Adds delay follow-up information']]" :key="f[0]"><td>{{l(f[1],f[2])}}</td><td>{{summary.sourceRows[f[0]]}}</td><td>{{l(f[3],f[4])}}</td></tr></tbody></table><p>{{l('各工作表的原始单元格值与来源行号已保存。补充表合并到对应订单；并非所有来源字段都已展现在主表。Excel 内嵌图片尚未提取。','Original cell values and source rows are retained for each worksheet. Supplementary rows link to their orders; not every source field appears in the order table. Embedded Excel images have not been extracted.')}}</p></details>
  <details v-for="sheet in summary?.workbookSheets||[]" :key="sheet.name" class="ops-definitions"><summary>{{l('表格汇总','Workbook summary')}} · {{sheet.name}}</summary><p>{{l('随表格保存同步更新；看板指标仍根据订单明细计算。','Updates with workbook saves; dashboard metrics are calculated from order details.')}}</p><div class="ops-scroll"><table><tbody><tr v-for="(row,r) in sheet.values" :key="r"><component :is="r===0?'th':'td'" v-for="(value,c) in row" :key="c">{{value??'—'}}</component></tr></tbody></table></div></details>
  <p v-if="!configured" class="ops-note">{{l('保存模块已加入，等待 Firebase 项目权限与登录配置。当前操作仍只保留在本次页面会话，请勿录入真实业务数据。','Saving is implemented, pending Firebase project access and sign-in setup. Current changes are session-only. Do not enter real business data.')}}</p>
  <form v-else-if="!connected" class="cloud-login" @submit.prevent="login"><label>{{l('已授权的邮箱','Authorized email')}}<input v-model="emailInput" type="email" required autocomplete="username"/></label><label>{{l('密码','Password')}}<input v-model="password" type="password" required autocomplete="current-password"/></label><button type="submit" :disabled="busy">{{l('登录并加载已保存记录','Sign in & load saved records')}}</button></form>
  <div v-else class="cloud-account"><span>{{email}} · {{l('保存版本','Saved revision')}} {{revision}}</span><button v-if="!publicTest" :disabled="busy" @click="emit('disconnect')">{{l('退出云端工作区','Leave cloud workspace')}}</button></div>
  <p v-if="error" role="alert" class="ops-error">{{error}}</p>
  <details v-if="deleted?.length" class="cloud-recycle"><summary>{{l('已删除的报发记录','Deleted dispatch records')}} · {{deleted.length}}</summary><div v-for="s in deleted" :key="s.id"><b>{{s.id}}</b><span>{{s.deleteReason}}</span><button :disabled="busy" @click="emit('restore',s)">{{l('恢复记录','Restore record')}}</button></div></details>
</section></template>
