<script setup>
import { ref,watch,computed } from 'vue'
import { Dialog,Button } from 'frappe-ui'
import { t as tr } from './i18n.mjs'
import { TODAY } from './domain.mjs'
import { label,remainingQty } from './reconciliation.mjs'
const props=defineProps({modelValue:Boolean,orders:Array,selected:Object,perform:Function})
const emit=defineEmits(['update:modelValue'])
const l=(zh,en)=>tr(label(zh,en)),date=ref(TODAY),eta=ref(''),mode=ref('海运'),reference=ref(''),container=ref(''),waybill=ref(''),courier=ref(''),carrier=ref(''),chassis=ref(''),position=ref(''),lines=ref([]),error=ref('')
const available=computed(()=>props.orders.filter(o=>remainingQty(o)>0))
watch(()=>props.modelValue,open=>{if(!open)return;const o=props.selected&&remainingQty(props.selected)>0?props.selected:available.value[0];lines.value=o?[{order:o.id,qty:remainingQty(o)}]:[];date.value=TODAY;eta.value='';mode.value=o?.mode||'海运';reference.value='';container.value='';waybill.value='';courier.value='';carrier.value='';chassis.value='';position.value='';error.value=''})
function candidates(index){const supplier=props.orders.find(o=>o.id===lines.value[0]?.order)?.supplier;return available.value.filter(o=>(!supplier||index===0||o.supplier===supplier)&&!lines.value.some((a,i)=>i!==index&&a.order===o.id))}
function add(){const o=candidates(lines.value.length)[0];if(o)lines.value.push({order:o.id,qty:remainingQty(o)})}
function save(){try{props.perform({date:date.value,eta:eta.value,mode:mode.value,ref:reference.value,containerNo:container.value,waybillNo:waybill.value,courierNo:courier.value,carrier:carrier.value,chassis:chassis.value,position:position.value,allocations:lines.value});emit('update:modelValue',false)}catch(e){error.value=e.message}}
</script>
<template><Dialog :model-value="modelValue" @update:model-value="emit('update:modelValue',$event)" :options="{title:l('登记业务报发','Record dispatch'),size:'xl'}"><template #body-content><div class="ops"><p class="ops-note">{{l('登记实际业务报发并分配到订单行。集装箱号、运单号或快递号至少填一项。正式发货过账仍在 SAP 完成。','Record the business dispatch and allocate it to order lines. Enter at least one container, waybill or courier reference. Formal PGI remains in SAP.')}}</p><div class="ops-form-grid"><label>{{l('报发日期','Dispatch date')}}<input v-model="date" type="date" :max="TODAY"/></label><label>{{l('运输方式','Transport mode')}}<select v-model="mode"><option value="海运">{{tr('海运')}}</option><option value="空运">{{tr('空运')}}</option><option value="快递">{{l('快递','Courier')}}</option></select></label><label>{{l('集装箱号','Container number')}}<input v-model="container"/></label><label>{{l('提单／空运单号','Bill of lading / air waybill')}}<input v-model="waybill"/></label><label>{{l('快递追踪号','Courier tracking number')}}<input v-model="courier"/></label><label>{{l('承运商／快递公司','Carrier / courier company')}}<input v-model="carrier"/></label><label>{{l('澳洲到仓 ETA（可留空）','AU warehouse ETA (optional)')}}<input v-model="eta" type="date"/></label><label>{{l('车架号','Chassis')}}<input v-model="chassis"/></label><label>{{l('装载位置','Loading position')}}<input v-model="position"/></label></div><div class="ops-detail-heading"><b>{{l('订单行数量分配','Order-line allocation')}}</b><Button variant="ghost" :disabled="!candidates(lines.length).length" @click="add">{{l('添加订单行','Add order line')}}</Button></div><div v-for="(a,i) in lines" :key="i" class="ops-allocation"><select v-model="a.order" :aria-label="l('订单行','Order line')"><option v-for="o in candidates(i)" :key="o.id" :value="o.id">{{o.po}} / {{o.item}} · {{o.part}}</option></select><input v-model="a.qty" type="number" min="0.001" step="any" :aria-label="l('本批数量','Batch quantity')"/><small>{{orders.find(o=>o.id===a.order)?.unit}}</small><button v-if="lines.length>1" @click="lines.splice(i,1)" :aria-label="l('删除分配','Remove allocation')">×</button></div><p v-if="!lines.length" class="ops-empty">{{l('当前没有剩余待发的订单','No orders have remaining dispatch quantity')}}</p><p v-if="error" role="alert" class="ops-error">{{error}}</p></div></template><template #actions><div class="modal-actions"><Button variant="outline" @click="emit('update:modelValue',false)">{{tr('取消')}}</Button><Button variant="solid" class="primary" :disabled="!lines.length" @click="save">{{l('保存报发并核对','Save dispatch & reconcile')}}</Button></div></template></Dialog></template>
