<script setup>
import { computed, ref, watch } from 'vue'
import { Button, Badge } from 'frappe-ui'
import { ArrowUpRight, ArrowRight, Search, RefreshCw, Plus, Ship, Plane, CircleAlert, CheckCheck, Download } from 'lucide-vue-next'
import { t as tr, dateLabel, language } from './i18n.mjs'
import { downloadExceptions } from './exception-export.mjs'
import { TODAY, openQty } from './domain.mjs'
import { money, percent } from './analytics.mjs'
import { KINDS, label, businessSummary, reportedQty, remainingQty, groupLabel, groupedQuantity, allocations, relatedShipments, priceReady,delayDays,shipmentDelayed } from './reconciliation.mjs'
const props=defineProps({view:String,orders:Array,shipments:Array,issues:Array,role:String,selection:Object,synced:Boolean})
const emit=defineEmits(['open-order','review','dispatch','sync','inspect','navigate','reset','clear-selection','shipment'])
const l=(zh,en)=>tr(label(zh,en))
const query=ref(''),owner=ref(''),source=ref(''),purpose=ref(''),shipping=ref(''),status=ref('all'),kind=ref(''),caseStatus=ref('active'),supplier=ref('')
watch(()=>props.view,()=>{query.value='';kind.value='';caseStatus.value='active'})
watch(()=>props.role,()=>{owner.value='';supplier.value=''})
const imported=computed(()=>props.orders.some(o=>o.imported))
const pageNumber=ref(1),pageSize=ref(40)
function clearOrderFilters(){query.value='';owner.value='';source.value='';purpose.value='';shipping.value='';supplier.value='';pageNumber.value=1}
function selectStatus(value){clearOrderFilters();status.value=value;emit('clear-selection')}
watch(()=>props.selection,value=>{if(value){clearOrderFilters();status.value='all'}},{immediate:true})
watch([query,owner,source,purpose,shipping,status,kind,caseStatus,supplier,pageSize,()=>props.view,()=>props.selection],()=>pageNumber.value=1)
const scope=computed(()=>props.orders.filter(o=>(!supplier.value||o.supplier===supplier.value)&&(!purpose.value||o.type===purpose.value)))
const summary=computed(()=>businessSummary(scope.value,props.shipments,props.issues))
const active=computed(()=>props.issues.filter(i=>i.status!=='已解决'))
const checks=computed(()=>props.issues.filter(i=>i.rule))
const problemOrders=computed(()=>new Set(active.value.map(c=>c.order)))
function matchesStatus(o,value){return value==='all'||value==='cancelled'&&o.cancelled||value==='open'&&openQty(o)>0||value==='completed'&&!o.cancelled&&o.qtyKnown!==false&&openQty(o)===0||value==='checks'&&problemOrders.value.has(o.id)}
const orderViews=computed(()=>[['all','全部记录','All records'],['open','未完成','Open'],['completed',imported.value?'台账已完成':'已收货',imported.value?'Ledger completed':'Received'],['cancelled','已取消','Cancelled'],['checks','有待处理','Needs action']].map(([key,zh,en])=>({key,title:l(zh,en),records:props.orders.filter(o=>matchesStatus(o,key))})))
const rows=computed(()=>scope.value.filter(o=>(!props.selection||props.selection.ids.includes(o.id))&&(!owner.value||o.buyer===owner.value)&&(!source.value||o.sourceType===source.value)&&(!shipping.value||o.mode===shipping.value)&&`${o.po} ${o.part} ${o.so||''} ${o.en} ${o.name}`.toLowerCase().includes(query.value.toLowerCase())&&matchesStatus(o,status.value)))
const tasks=computed(()=>props.issues.filter(c=>(props.view!=='data'||c.rule)&&(!kind.value||c.kind===kind.value)&&(!owner.value||c.owner===owner.value)&&(caseStatus.value==='all'||caseStatus.value==='active'&&c.status!=='已解决'||caseStatus.value==='closed'&&c.status==='已解决')&&`${c.id} ${props.orders.find(o=>o.id===c.order)?.po} ${tr(c.title)}`.toLowerCase().includes(query.value.toLowerCase())))
const transport=computed(()=>imported.value?['海运','空运','快递'].map(mode=>{const os=summary.value.open.filter(o=>o.mode===mode);return {mode,rows:os.map(order=>({order})),count:os.length,value:null,groups:groupedQuantity(os,remainingQty)}}):['海运','空运','快递'].map(mode=>{const rs=summary.value.transitRows.filter(r=>r.shipment.mode===mode);return{mode,rows:rs,count:new Set(rs.map(r=>r.shipment.id)).size,value:rs.filter(r=>priceReady(r.order)).reduce((n,r)=>n+r.qty*r.order.unitPrice/(r.order.priceUnit||1),0),groups:rs.reduce((n,r)=>{n[r.order.unit]=(n[r.order.unit]||0)+r.qty;return n},{})}}))
const age=computed(()=>[[0,15],[16,30],[31,60],[61,90],[91,Infinity]].map(([min,max])=>({label:max===Infinity?'>90':`${min}–${max}`,rows:summary.value.open.filter(o=>{const d=(Date.parse(TODAY)-Date.parse(o.created))/86400000;return d>=min&&d<=max})})))
const shipmentRows=computed(()=>props.shipments.filter(s=>allocations(s).some(a=>props.orders.some(o=>o.id===a.order))))
const listTotal=computed(()=>props.view==='orders'?rows.value.length:props.view==='shipments'?shipmentRows.value.length:tasks.value.length)
const maxPage=computed(()=>Math.max(1,Math.ceil(listTotal.value/pageSize.value)))
watch(maxPage,value=>{pageNumber.value=Math.min(pageNumber.value,value)})
function goToPage(value){pageNumber.value=Math.max(1,Math.min(maxPage.value,Math.trunc(Number(value)||1)))}
const pagedRows=computed(()=>rows.value.slice((pageNumber.value-1)*pageSize.value,pageNumber.value*pageSize.value))
const pagedTasks=computed(()=>tasks.value.slice((pageNumber.value-1)*pageSize.value,pageNumber.value*pageSize.value))
const pagedShipments=computed(()=>shipmentRows.value.slice((pageNumber.value-1)*pageSize.value,pageNumber.value*pageSize.value))
function order(id){return props.orders.find(o=>o.id===id)}
function open(id,tab='overview'){const o=order(id);if(o)emit('open-order',o,tab)}
function inspect(records,title){emit('inspect',{ids:[...new Set(records.map(o=>o.id))],label:title})}
function relatedCases(o){return active.value.filter(i=>i.order===o.id)}
function fulfillment(o){if(o.cancelled)return l('已取消','Cancelled');if(o.imported)return remainingQty(o)>0?(reportedQty(o)>0?tr('部分发运'):l('待发运','To dispatch')):l('台账已报发','Ledger: dispatched');return o.received>=o.qty?tr('已收货'):reportedQty(o)>0?reportedQty(o)<o.qty?tr('部分发运'):l('已报发','Reported dispatched'):tr(o.status)}
function shipmentGroups(s){return groupLabel(allocations(s).filter(a=>order(a.order)).reduce((out,a)=>{const u=order(a.order).unit||'EA';out[u]=(out[u]||0)+a.qty;return out},{}))}
function exportView(){
  const quote=v=>'"'+String(/^[=+@-]/.test(String(v))?"'"+v:v).replaceAll('"','""')+'"'
  const headers=['PO','Item','Material','Owner','Purpose','Source','Unit','Ordered','Reported','SAP PGI','Remaining dispatch','Promised dispatch','SO','Open tasks']
  const records=rows.value.map(o=>[o.po,o.item,o.part,o.buyer,tr(o.type),l(o.sourceType==='make'?'自制件':'外购件',o.sourceType==='make'?'In-house':'Purchased'),o.unit,o.qty,reportedQty(o),o.shipped,remainingQty(o),o.promisedEtd,o.so,relatedCases(o).length])
  const url=URL.createObjectURL(new Blob(['\uFEFF'+[headers,...records].map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Regent-demo-orders.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
const exceptionExportError=ref(''),exceptionExportNotice=ref('')
function exportExceptionView(){
  exceptionExportError.value='';exceptionExportNotice.value=''
  if (!tasks.value.length) return
  try {
    downloadExceptions(tasks.value,props.orders,{language:language.value})
    exceptionExportNotice.value=l('已导出当前筛选的 '+tasks.value.length+' 条异常（含全部页）。','Exported all '+tasks.value.length+' matching issues across all pages.')
  } catch {
    exceptionExportError.value=l('异常清单导出失败，请重试。','Could not export the exception list. Please retry.')
  }
}
</script>

<template>
<div class="ops">
  <template v-if="view==='overview'">
    <div class="ops-toolbar"><div class="ops-title"><h1>{{tr('总览看板')}}</h1><small>{{TODAY}} · {{imported?l('实时协作／09.04 初始化台账','Live collaboration / 04 Sep initial ledger'):l('模拟业务快照','Simulated snapshot')}}</small></div><div class="ops-filters"><select v-if="role==='buyer'" v-model="supplier" :aria-label="tr('供应商')"><option value="">{{tr('全部供应商')}}</option><option v-for="s in [...new Set(orders.map(o=>o.supplier))]" :key="s">{{s}}</option></select><select v-model="purpose" :aria-label="tr('订单类型')"><option value="">{{l('全部用途','All purposes')}}</option><option value="生产订单">{{tr('生产订单')}}</option><option value="售后配件">{{tr('售后配件')}}</option><option v-if="imported" value="用途待确认">{{l('用途待确认','Purpose unconfirmed')}}</option></select><Button variant="outline" @click="emit('reset')"><RefreshCw :size="14"/>{{tr('重置演示')}}</Button></div></div>
    <div v-if="imported" class="ops-ledger-nav"><span>{{l('完整台账','Full ledger')}}</span><button v-for="v in orderViews.slice(0,4)" :key="v.key" @click="inspect(v.records,v.title)">{{v.title}} <b>{{v.records.length.toLocaleString()}}</b><ArrowUpRight :size="13"/></button></div>
    <div class="ops-kpis">
      <button @click="inspect(summary.open,l('未完成订单','Open orders'))"><small>{{l('未完成 PO／订单行','Open POs / lines')}}</small><strong>{{summary.poCount}}<span>/ {{summary.open.length}}</span></strong><footer>{{imported?l('按台账剩余待发口径','Ledger remaining dispatch basis'):l('未全部收货','Not fully received')}}<ArrowUpRight :size="15"/></footer></button>
      <button class="featured" @click="inspect(summary.transitRows.map(r=>r.order),l('已核实在途','Verified in transit'))"><small>{{l('已核实在途批次','Verified transit batches')}}</small><strong>{{imported?'—':summary.transit.length}}<span>{{l('批','batches')}}</span></strong><footer>{{imported?l('等待 SAP 与物流核对','Awaiting SAP / logistics verification'):money(summary.transitValue)+' · AUD'}}<ArrowUpRight :size="15"/></footer></button>
      <button @click="inspect(scope.filter(o=>remainingQty(o)>0),l('剩余待发','Remaining to dispatch'))"><small>{{l('剩余待发行','Lines awaiting dispatch')}}</small><strong>{{scope.filter(o=>remainingQty(o)>0).length}}<span>{{tr('行')}}</span></strong><footer>{{l('按报发量计算','Based on reported dispatch')}}<ArrowUpRight :size="15"/></footer></button>
      <button @click="inspect(summary.risk,tr('交期风险'))"><small>{{tr('交期风险')}}</small><strong class="ops-amber">{{summary.risk.length}}<span>{{tr('行')}}</span></strong><footer>{{l('发运承诺／到仓风险','Dispatch / arrival risk')}}<ArrowUpRight :size="15"/></footer></button>
      <button @click="inspect(summary.known,l('已确认价格覆盖','Confirmed price coverage'))"><small>{{l('已确认未交货值 · AUD','Confirmed open value · AUD')}}</small><strong class="value">{{summary.known.length?money(summary.openValue):'—'}}</strong><footer>{{summary.known.length}} / {{summary.open.length}} {{l('行已覆盖','lines covered')}}<ArrowUpRight :size="15"/></footer></button>
    </div>
    <div class="ops-summary-grid">
      <section class="ops-panel"><header><h2>{{imported?l('未完成记录运输分类','Open records by transport'):l('运输与数量','Transport & quantities')}}</h2><Badge theme="blue">{{l('单位分组','By unit')}}</Badge></header><div class="ops-mode" v-for="m in transport" :key="m.mode"><button @click="inspect(m.rows.map(r=>r.order),tr(m.mode))"><component :is="m.mode==='海运'?Ship:Plane" :size="17"/><b>{{tr(m.mode)}}</b><span>{{m.count}} {{imported?l('行','lines'):l('批','batches')}}</span><strong>{{m.value===null?'—':money(m.value)}}</strong></button><div class="ops-bar"><i :style="{width:percent(m.count,imported?summary.open.length:summary.transit.length)+'%',background:m.mode==='海运'?'#256b9a':'#13a394'}"></i></div><small>{{groupLabel(m.groups)}}</small></div><div class="ops-inline-note"><span>{{l('剩余待发','Remaining to dispatch')}}</span><b>{{groupLabel(summary.remaining)}}</b></div><div class="ops-inline-note"><span>{{l('SAP 已收货','SAP receipts')}}</span><b>{{groupLabel(summary.received)}}</b></div><p v-if="imported" class="ops-note">{{scope.filter(o=>!o.quantityComparable&&openQty(o)>0).length}} {{l('条未完成记录的单位／关联待核实，暂不计入数量合计。','open records have unverified units or links and are excluded from quantity totals.')}}</p></section>
      <section class="ops-panel"><header><h2>{{l('订单用途与来源','Purpose & source')}}</h2><small>{{summary.open.length}} {{tr('行')}}</small></header><button v-for="p in (imported?['生产订单','售后配件','用途待确认']:['生产订单','售后配件'])" :key="p" class="ops-category" @click="inspect(summary.open.filter(o=>o.type===p),tr(p))"><div><b>{{p==='用途待确认'?l('用途待确认','Purpose unconfirmed'):tr(p)}}</b><span>{{summary.open.filter(o=>o.type===p).length}} {{tr('行')}}</span></div><div class="ops-bar"><i :style="{width:percent(summary.open.filter(o=>o.type===p).length,summary.open.length)+'%'}"></i></div></button><div class="ops-source-grid"><button v-for="s in summary.source" :key="s.key" @click="inspect(s.rows,l(s.key==='buy'?'外购件':'自制件',s.key==='buy'?'Purchased':'In-house'))"><small>{{l(s.key==='buy'?'外购件':'自制件',s.key==='buy'?'Purchased':'In-house')}}</small><strong>{{s.rows.length}} <small>{{tr('行')}}</small></strong></button></div><p class="ops-note">{{l('用途与来源分别分类；合同供应商与上游参考信息分开维护。','Purpose and source are separate. Contract supplier and upstream references are maintained independently.')}}</p></section>
      <section class="ops-panel"><header><h2>{{tr('未完成订单账龄')}}</h2><small>{{l('订单行','Order lines')}}</small></header><table><thead><tr><th>{{l('天数','Days')}}</th><th>{{tr('生产')}}</th><th>{{tr('售后')}}</th><th v-if="imported">{{l('待定','Unclassified')}}</th><th>{{tr('合计')}}</th></tr></thead><tbody><tr v-for="a in age" :key="a.label"><td><button class="ops-link" @click="inspect(a.rows,a.label)">{{a.label}} <ArrowUpRight :size="12"/></button></td><td>{{a.rows.filter(o=>o.type==='生产订单').length}}</td><td>{{a.rows.filter(o=>o.type==='售后配件').length}}</td><td v-if="imported">{{a.rows.filter(o=>o.type==='用途待确认').length}}</td><td><b>{{a.rows.length}}</b></td></tr></tbody></table><p class="ops-note">{{l('账龄从下单日起计算，不等同于延期。','Age is measured from order creation, not lateness.')}}</p></section>
    </div>
    <div class="ops-bottom-grid"><section class="ops-panel"><header><h2>{{l('近期装运与到仓','Upcoming shipments & arrivals')}}</h2><Button variant="ghost" @click="emit('navigate','shipments')">{{l('全部批次','All batches')}}<ArrowRight :size="14"/></Button></header><div class="ops-scroll"><table><thead><tr><th>{{l('批次／运输','Batch / mode')}}</th><th>{{l('数量 · 原单位','Quantity · original unit')}}</th><th>{{l('SAP 状态','SAP status')}}</th><th>{{l('澳洲到仓 ETA','AU warehouse ETA')}}</th><th></th></tr></thead><tbody><tr v-for="s in summary.batches.slice().sort((a,b)=>(a.eta||'9999').localeCompare(b.eta||'9999')).slice(0,3)" :key="s.id"><td><b>{{s.id}}</b><small>{{tr(s.mode)}} · {{s.ref}}</small></td><td>{{shipmentGroups(s)}}</td><td><Badge :theme="s.sapPosted?'green':'orange'">{{l(s.sapPosted?'已关联过账':'报发待核实',s.sapPosted?'PGI linked':'Report unverified')}}</Badge></td><td>{{s.eta?dateLabel(s.eta):l('待补充','Not provided')}}<small v-if="shipmentDelayed(s)" class="ops-amber">{{l('延期跟进','Delay follow-up')}} {{delayDays(s)>0?'+'+delayDays(s)+'d':''}}</small></td><td><button class="ops-link" @click="open(allocations(s).find(a=>order(a.order)).order,'logistics')" :aria-label="l('查看批次','View batch')"><ArrowUpRight :size="17"/></button></td></tr></tbody></table></div><p v-if="!summary.batches.length" class="ops-empty">{{l('当前范围暂无装运批次','No shipments in this scope')}}</p></section><section class="ops-panel"><header><h2>{{l('需要关注','Attention needed')}}</h2><CircleAlert :size="17"/></header><button class="ops-attention" @click="inspect(scope.filter(o=>summary.unresolved.some(c=>c.order===o.id)),l('待处理订单','Orders needing action'))"><span>{{l('涉及订单行','Affected order lines')}}</span><b>{{new Set(summary.unresolved.map(c=>c.order)).size}}</b><ArrowUpRight :size="14"/></button><button class="ops-attention" @click="emit('navigate','exceptions')"><span>{{l('未关闭事项','Open tasks')}}</span><b>{{summary.unresolved.length}}</b><ArrowRight :size="14"/></button><button class="ops-attention" @click="inspect(summary.unpriced,l('价格待确认','Price verification'))"><span>{{l('货值暂未覆盖','Value not yet covered')}}</span><b>{{summary.unpriced.length}} {{tr('行')}}</b><ArrowUpRight :size="14"/></button><button class="ops-attention" @click="emit('navigate',role==='buyer'?'data':'shipments')"><span>{{l('报发待 SAP 核实','Reports awaiting SAP')}}</span><b>{{summary.pendingBatches.length}} {{l('批','batches')}}</b><ArrowRight :size="14"/></button></section></div>
    <details class="ops-definitions"><summary>{{l('统计口径与数据来源','Definitions & data sources')}}</summary><p>{{l('台账已报发不代表 SAP 已收货。货值仅包括已确认价格；单位或关联不明的数量不相加。在途须有 SAP 及物流依据。','Ledger dispatch does not prove SAP receipt. Value includes confirmed prices only; unverified units or links are excluded from quantity sums. Transit requires SAP and logistics evidence.')}}</p></details>
  </template>

  <template v-else-if="view==='orders'">
    <div v-if="selection" class="ops-scope"><span>{{l('当前下钻范围','Drill-down scope')}}: {{tr(selection.label)}} · {{selection.ids.length}} {{tr('行')}}</span><Button variant="ghost" @click="emit('clear-selection')">{{l('清除范围','Clear scope')}}</Button></div>
    <div class="ops-toolbar"><div class="ops-tabs"><button v-for="v in orderViews" :key="v.key" :class="{active:!selection&&status===v.key}" :aria-pressed="!selection&&status===v.key" @click="selectStatus(v.key)">{{v.title}} <b>{{v.records.length.toLocaleString()}}</b></button></div><div class="ops-filters"><Button variant="outline" @click="exportView">{{tr('导出当前视图')}}</Button><Button variant="solid" class="primary" @click="emit('dispatch')"><Plus :size="15"/>{{l('登记业务报发','Record dispatch')}}</Button></div></div>
    <div class="ops-filters ops-filter-panel"><label class="ops-search"><Search :size="16"/><input v-model="query" :placeholder="l('搜索 PO、SO、物料','Search PO, SO, material')"/></label><select v-model="owner" :aria-label="l('责任人筛选','Filter owner')"><option value="">{{l('全部责任人','All owners')}}</option><option v-for="b in [...new Set(orders.map(o=>o.buyer))]" :key="b">{{b}}</option></select><select v-model="purpose" :aria-label="l('用途筛选','Filter purpose')"><option value="">{{l('全部用途','All purposes')}}</option><option value="生产订单">{{tr('生产订单')}}</option><option value="售后配件">{{tr('售后配件')}}</option><option v-if="imported" value="用途待确认">{{l('用途待确认','Purpose unconfirmed')}}</option></select><select v-model="source" :aria-label="l('来源筛选','Filter source')"><option value="">{{l('全部来源','All sources')}}</option><option value="buy">{{l('外购件','Purchased')}}</option><option value="make">{{l('自制件','In-house')}}</option></select><select v-model="shipping" :aria-label="l('运输筛选','Filter transport')"><option value="">{{tr('全部运输')}}</option><option value="海运">{{tr('海运')}}</option><option value="空运">{{tr('空运')}}</option><option value="快递">{{l('快递','Courier')}}</option></select><small>{{rows.length}} {{tr('行')}}</small></div>
    <div class="ops-pagination ops-pagination-top"><span>{{l('显示','Showing')}} {{rows.length?(pageNumber-1)*pageSize+1:0}}–{{Math.min(pageNumber*pageSize,rows.length)}} / {{rows.length.toLocaleString()}} {{l('条记录','records')}}</span><label>{{l('每页','Per page')}} <select v-model.number="pageSize" :aria-label="l('每页记录数','Records per page')"><option :value="40">40</option><option :value="100">100</option></select></label><Button variant="outline" :disabled="pageNumber<=1" @click="goToPage(pageNumber-1)">{{l('上一页','Previous')}}</Button><label><input type="number" :value="pageNumber" min="1" :max="maxPage" :aria-label="l('页码','Page number')" @change="goToPage($event.target.value);$event.target.value=pageNumber"/> / {{maxPage}}</label><Button variant="outline" :disabled="pageNumber>=maxPage" @click="goToPage(pageNumber+1)">{{l('下一页','Next')}}</Button></div>
    <p v-if="imported" class="ops-note">{{l('台账已完成表示台账剩余待发为零，不代表 SAP 已收货。上方分类显示完整台账数量；切换分类会清除其他筛选。','Ledger completed means no remaining dispatch in the ledger, not confirmed SAP receipt. Tabs count the full ledger; switching tabs clears other filters.')}}</p>
    <section class="ops-panel ops-scroll"><table class="ops-orders-table"><thead><tr><th>PO / {{l('行','item')}}</th><th>{{l('物料与描述','Material / description')}}</th><th>{{l('责任人／来源','Owner / source')}}</th><th>{{l('订购／报发／待发','Ordered / reported / left')}}</th><th>{{l('承诺发运','Promised dispatch')}}</th><th>{{l('运输／批次','Mode / batches')}}</th><th>{{l('履约状态','Fulfillment')}}</th><th>{{l('待处理','Action needed')}}</th></tr></thead><tbody><tr v-for="o in pagedRows" :key="o.id"><td><button class="ops-link" @click="emit('open-order',o)">{{o.po}}</button><small>{{o.item}}</small></td><td><b>{{o.part}}</b><small class="ops-description">{{tr(o.name)}}</small><small v-if="o.sapPart!==o.soPart" class="ops-amber">{{l('跨主体料号','Cross-entity codes')}}</small></td><td>{{o.buyer}}<small>{{l(o.sourceType==='make'?'自制件':'外购件',o.sourceType==='make'?'In-house':'Purchased')}} · {{o.type==='用途待确认'?l('用途待确认','Purpose unconfirmed'):tr(o.type)}}</small></td><td class="ops-quantities"><b>{{o.qty}}</b> / {{reportedQty(o)}} / <b>{{remainingQty(o)}}</b><small>{{o.unit}} · SAP {{o.shipped??'—'}}</small></td><td :class="{'ops-amber':remainingQty(o)>0&&(!o.promisedEtd||o.promisedEtd<TODAY)}">{{o.promisedEtd?dateLabel(o.promisedEtd):l('待确认','Unconfirmed')}}<small>{{l('澳洲 ETA','AU ETA')}} {{o.eta?dateLabel(o.eta):'—'}}</small></td><td>{{tr(o.mode)}}<small>{{relatedShipments(o,shipments).length}} {{l('批','batches')}}</small></td><td><Badge :theme="reportedQty(o)>0?'blue':'gray'">{{fulfillment(o)}}</Badge></td><td><button v-if="relatedCases(o).length" class="ops-case-link" @click="emit('open-order',o,'activity')">{{relatedCases(o).length}} {{l('项待处理','open tasks')}}<small>{{tr(relatedCases(o)[0].title)}}</small></button><button v-else-if="o.imported&&o.importChecks?.length" class="ops-case-link" @click="emit('open-order',o,'overview')">{{l('初始化核对项','Initial review items')}} · {{o.importChecks.length}}</button><span v-else class="ops-green">{{o.imported?l('暂无待办','No open tasks'):l('核对通过','Checks passed')}}</span></td></tr><tr v-if="!rows.length"><td colspan="8" class="ops-empty">{{l('没有符合筛选条件的订单','No orders match these filters')}}</td></tr></tbody></table></section>
    <p class="ops-note">{{l('报发不等于 SAP 过账；待发按业务报发量计算。价格、收货和分批记录可在订单详情查看。','Reported dispatch is separate from SAP PGI. Remaining dispatch uses reported quantities. Open details for prices, receipts and batch allocations.')}}</p>
  </template>

  <template v-else-if="view==='data'||view==='exceptions'">
    <p v-if="imported" class="ops-note">{{l('当前按已导入的 SAP 参考数据核对；后续 SAP 原始快照尚未自动接入此清单。导出中的 SAP 数据时间表示参考数据日期。','Checks use imported SAP reference data. Later raw SAP snapshots are not yet applied to this list. SAP data dates in exports refer to the reference data.')}}</p>
    <div v-if="view==='data'&&!imported" class="ops-sync"><div><b>{{l('SAP 与平台核对','SAP / platform reconciliation')}}</b><small>{{l('模拟 SAP 快照','Simulated SAP snapshot')}} · {{synced?'09/08 10:00':'09/08 09:00'}} · {{l('初始化来源截至','Initial source as of')}} 09/04</small></div><Button variant="outline" :disabled="synced" @click="emit('sync')"><RefreshCw :size="15"/>{{l(synced?'示例快照已应用':'模拟接收后续 SAP 快照',synced?'Demo snapshot applied':'Simulate later SAP snapshot')}}</Button></div>
    <div class="ops-check-metrics"><div><small>{{l('未关闭事项','Open tasks')}}</small><strong>{{(view==='data'?checks:issues).filter(i=>i.status!=='已解决').length}}</strong></div><div><small>{{l('涉及订单行 · 去重','Affected lines · unique')}}</small><strong>{{new Set((view==='data'?checks:issues).filter(i=>i.status!=='已解决').map(c=>c.order)).size}}</strong></div><div><small>{{l('已通过核对／已解决','Passed / resolved')}}</small><strong>{{(view==='data'?checks:issues).filter(i=>i.status==='已解决').length}}</strong></div><div><small>{{l('处理方式','Processing')}}</small><b>{{l('规则核对 + 人员确认','Rules + human review')}}</b></div></div>
    <div class="ops-filters ops-filter-panel"><label class="ops-search"><Search :size="16"/><input v-model="query" :placeholder="l('搜索任务或 PO','Search task or PO')"/></label><select v-model="kind" :aria-label="l('问题类型','Issue type')"><option value="">{{l('全部问题类型','All issue types')}}</option><option v-for="(title,key) in KINDS" :key="key" :value="key">{{tr(title)}}</option></select><select v-model="owner" :aria-label="l('任务责任人','Task owner')"><option value="">{{l('全部责任人','All owners')}}</option><option v-for="b in [...new Set(issues.map(i=>i.owner))]" :key="b">{{b}}</option></select><select v-model="caseStatus" :aria-label="l('任务状态','Task status')"><option value="active">{{l('未关闭','Open')}}</option><option value="closed">{{l('已解决','Resolved')}}</option><option value="all">{{l('全部状态','All states')}}</option></select><Button variant="outline" :disabled="!tasks.length" @click="exportExceptionView" :title="l('导出当前筛选的全部异常，不受分页影响','Export all matching issues across every page')"><Download :size="15"/>{{l('导出异常 Excel','Export exceptions to Excel')}}</Button><small>{{tasks.length}} {{l('条异常','issues')}}</small></div>
    <p v-if="exceptionExportNotice" class="ops-note" role="status">{{exceptionExportNotice}}</p><p v-if="exceptionExportError" class="ops-error" role="alert">{{exceptionExportError}}</p>
    <section class="ops-panel ops-scroll"><table class="ops-case-table"><thead><tr><th>{{l('问题与比对摘要','Issue & comparison')}}</th><th>PO / {{l('行','item')}}</th><th>{{l('责任人／期限','Owner / due')}}</th><th>{{l('状态','Status')}}</th><th>{{l('下一步','Next action')}}</th></tr></thead><tbody><tr v-for="c in pagedTasks" :key="c.id"><td><b>{{tr(c.title)}}</b><small>{{c.userEntered?c.detail:tr(c.detail)}}</small><small v-if="c.note">{{c.noteUserEntered||c.rule?c.note:tr(c.note)}}</small></td><td><button class="ops-link" @click="open(c.order,view==='data'?'overview':'activity')">{{order(c.order)?.po}}</button><small>{{order(c.order)?.item}}</small></td><td>{{c.owner}}<small :class="{'ops-amber':c.due<TODAY&&c.status!=='已解决'}">{{c.due}}</small></td><td><Badge :theme="c.status==='已解决'?'green':c.priority==='高'?'orange':'gray'">{{tr(c.status)}}</Badge></td><td><Button v-if="c.status!=='已解决'" variant="outline" @click="emit('review',c)">{{l(role==='buyer'?'核对与处理':'查看与跟进',role==='buyer'?'Review & act':'View & follow up')}}</Button><Button v-else variant="ghost" @click="open(c.order,'activity')">{{l('查看依据','View evidence')}}</Button></td></tr><tr v-if="!tasks.length"><td colspan="5" class="ops-empty"><CheckCheck :size="24"/>{{l('当前筛选下没有待显示的事项','No tasks match this view')}}</td></tr></tbody></table></section>
    <details v-if="view==='data'" class="ops-definitions" open><summary>{{l('字段归属与初始化规则','Field ownership & initialization')}}</summary><div class="ops-ownership"><div><b>SAP</b><p>{{l('正式 PO／SO、订购数量、价格、单位、发货及收货过账。保留原值和同步时间。','Formal PO/SO, ordered quantities, prices, units, PGI and receipts. Original values and sync times are retained.')}}</p></div><div><b>{{l('协作平台','Collaboration platform')}}</b><p>{{l('承诺、国内 ETA、业务报发、装载位置、备注、异常处理。SAP 同步不覆盖这些协作记录。','Commitments, China ETA, dispatch reports, loading positions, notes and issue handling. SAP sync does not overwrite these records.')}}</p></div><div><b>{{l('Excel 初始化','Excel initialization')}}</b><p>{{l('首次导入保留文件行号和原值，后续协作在平台维护。','Initial import retains source rows and originals; ongoing collaboration is maintained in the platform.')}}</p></div></div><p v-if="!imported">{{l('模拟快照只为示例批次 SHP-DEMO-003 补充 SAP 过账；不会把新登记的报发自动当作 SAP 发货。正式环境需要内网同步服务。','The demo snapshot supplies PGI only for SHP-DEMO-003. New dispatch reports are never automatically treated as SAP PGI. Production requires an internal sync service.')}}</p></details>
  </template>

  <template v-else-if="view==='shipments'">
    <div class="ops-toolbar"><small>{{shipmentRows.length}} {{imported?l('条报发记录／累计汇总；不能视为逐批明细','dispatch records / cumulative summaries; not individual shipment history'):l('批次 · 一个批次可关联多条订单','batches · each can include multiple order lines')}}</small><Button variant="solid" class="primary" @click="emit('dispatch')"><Plus :size="15"/>{{l('登记业务报发','Record dispatch')}}</Button></div>
    <section v-for="s in pagedShipments" :key="s.id" class="ops-panel ops-batch"><header><h2>{{s.id}} <small>{{tr(s.mode)}} · {{s.ref}}</small></h2><div class="ops-filters"><Badge :theme="s.sapPosted?'green':'orange'">{{l(s.sapPosted?'SAP 过账已关联':'业务报发 · 待核实',s.sapPosted?'SAP PGI linked':'Reported · unverified')}}</Badge><Button variant="outline" @click="emit('shipment',s)">{{l('维护物流与延期','Edit logistics & delay')}}</Button></div></header><div class="ops-batch-facts"><div><small>{{l('报发日期','Reported date')}}</small><b>{{s.reportedAt||s.etd}}</b></div><div><small>{{l('SAP 过账日期','SAP PGI date')}}</small><b>{{s.pgiAt||'—'}}</b></div><div><small>{{l('澳洲到仓 ETA','AU warehouse ETA')}}</small><b>{{s.eta||l('待补充','Not provided')}}</b><small v-if="shipmentDelayed(s)" class="ops-amber">{{l('延期跟进','Delay follow-up')}} {{delayDays(s)>0?'+'+delayDays(s)+'d':''}}</small></div><div><small>{{l('车架／装载位置','Chassis / load position')}}</small><b>{{s.chassis||'—'}} / {{tr(s.position)||'—'}}</b></div></div><div class="ops-tracking-strip"><span>{{l('集装箱','Container')}} <b>{{s.containerNo||'—'}}</b></span><span>{{l('提单／空运单','B/L / AWB')}} <b>{{s.waybillNo||'—'}}</b></span><span>{{l('快递号','Courier')}} <b>{{s.courierNo||'—'}}</b></span><span>{{l('承运商','Carrier')}} <b>{{tr(s.carrier)||'—'}}</b></span></div><p v-if="s.delayReason||s.nextAction" class="ops-note">{{l('延期原因／下一步','Delay reason / next action')}}: {{s.delayReason||'—'}} / {{s.nextAction||'—'}}</p><table><thead><tr><th>{{l('关联 PO／行','Linked PO / line')}}</th><th>{{l('物料','Material')}}</th><th>{{l('分配数量','Allocated quantity')}}</th><th>{{l('已关联收货','Allocated receipts')}}</th></tr></thead><tbody><tr v-for="a in allocations(s).filter(a=>order(a.order))" :key="a.order"><td><button class="ops-link" @click="open(a.order,'logistics')">{{order(a.order).po}} / {{order(a.order).item}}</button></td><td>{{order(a.order).part}}</td><td>{{a.qty}} {{order(a.order).unit}}</td><td>{{a.receivedQty??'—'}} {{order(a.order).unit}}</td></tr></tbody></table></section>
  </template>
<div v-if="['orders','shipments','data','exceptions'].includes(view)&&listTotal>pageSize" class="ops-pagination"><span>{{listTotal}} {{l('条记录','records')}} · {{pageNumber}} / {{maxPage}}</span><Button variant="outline" :disabled="pageNumber<=1" @click="pageNumber--">{{l('上一页','Previous')}}</Button><Button variant="outline" :disabled="pageNumber*pageSize>=listTotal" @click="pageNumber++">{{l('下一页','Next')}}</Button></div>
</div>
</template>
