<script setup>
import { ref, watch } from 'vue'
import { Button, Badge } from 'frappe-ui'
import { t as tr } from './i18n.mjs'
import { label, factsFor, remainingQty, reportedQty, relatedShipments, allocations, priceReady, delayDays, shipmentDelayed, SHIPMENT_FIELDS } from './reconciliation.mjs'
const props=defineProps({order:Object,shipments:Array,issues:Array,tab:String,role:String,saveDates:Function})
const emit=defineEmits(['review','dispatch','shipment'])
const l=(zh,en)=>tr(label(zh,en))
const fieldLabels={seq:['序号','Sequence'],mode:['运输方式','Transport'],po:['采购订单','Purchase order'],line:['订单行','Order line'],van:['车架','Chassis'],description_zh:['中文描述','Chinese description'],description_en:['英文描述','English description'],supplier_reference:['上游供应商／参考','Upstream supplier / reference'],material:['料号','Material'],qty:['订购数量','Ordered quantity'],category:['外购／自制','Purchased / in-house'],so:['销售订单引用','SO reference'],buyer:['采购员','Purchaser'],ordered:['下单日期','Order date'],agreed_etd:['原约定发运','Agreed dispatch'],planned_etd:['计划发运','Planned dispatch'],manager:['跟进人','Coordinator'],eta_china:['国内到货','China inbound'],actual_ship:['台账报发日期','Ledger dispatch date'],shipped:['累计报发','Cumulative dispatched'],remaining:['剩余待发','Remaining dispatch'],loaded_van:['装载车架','Loaded chassis'],location:['装载位置','Loading position'],container:['集装箱号','Container number'],awb:['空运单号','Air waybill'],completion:['台账完成标记','Ledger completion marker'],notes:['备注','Notes']}
const fieldName=k=>fieldLabels[k]?l(...fieldLabels[k]):k
const etd=ref(''),china=ref(''),auEta=ref(''),reason=ref(''),delayStatus=ref('unknown'),delayReason=ref(''),plan=ref(''),error=ref('')
watch(()=>props.order,o=>{etd.value=o?.promisedEtd||'';china.value=o?.chinaEta||'';auEta.value=o?.eta||'';reason.value='';delayStatus.value=o?.dispatchDelayStatus||'unknown';delayReason.value=o?.dispatchDelayReason||'';plan.value=o?.remainingPlan||'';error.value=''}, {immediate:true})
async function save(){try{await props.saveDates(props.order,{etd:etd.value,china:china.value,auEta:props.order.imported?auEta.value:undefined,reason:reason.value,delayStatus:delayStatus.value,delayReason:delayReason.value,plan:plan.value});reason.value='';error.value=''}catch(e){error.value=e.message}}
</script>
<template><div class="ops ops-record">
  <template v-if="tab==='overview'">
    <details v-if="order.imported" class="ops-definitions"><summary>{{l('Excel 原始字段与核对依据','Excel source fields & review evidence')}}</summary><p>{{order.importNotes}}</p><p v-for="e in order.importEvidence" :key="e.file+e.row">{{e.file}} · {{e.sheet}} · {{l('行','row')}} {{e.row}}</p><table><tbody><tr v-for="(v,k) in order.importFields" :key="k"><th>{{fieldName(k)}}</th><td>{{v??'—'}}</td></tr></tbody></table><article v-for="c in order.importChecks" :key="c.id"><b>{{tr(c.title)}}</b><pre class="import-evidence">{{JSON.stringify(c.detail,null,2)}}</pre></article></details>
    <div class="ops-record-summary"><div><small>{{l('订购','Ordered')}}</small><b>{{order.qty}} {{order.unit||'EA'}}</b></div><div><small>{{l('业务报发','Reported dispatch')}}</small><b>{{reportedQty(order)}} {{order.unit||'EA'}}</b></div><div><small>{{l('剩余待发','To dispatch')}}</small><b>{{remainingQty(order)}} {{order.unit||'EA'}}</b></div><div><small>{{l('SAP 收货','SAP receipts')}}</small><b>{{order.received??'—'}} {{order.unit||'EA'}}</b></div></div>
    <div class="ops-record-refs"><div><small>{{l('澳洲 PO／行','AU PO / line')}}</small><b>{{order.po}} / {{order.item}}</b></div><div><small>{{l('工厂 SO','Factory SO')}}</small><b>{{order.so||l('待关联','Not linked')}}</b></div><div><small>{{l('合同供应商／采购员','Contract supplier / buyer')}}</small><b>{{order.supplier}} / {{order.buyer}}</b></div><div><small>{{l('用途／来源','Purpose / source')}}</small><b>{{tr(order.type)}} / {{l(order.sourceType==='make'?'自制件':'外购件',order.sourceType==='make'?'In-house':'Purchased')}}</b></div></div>
    <div class="ops-detail-heading"><h3>{{l('原始数据与采用口径','Source values & adopted basis')}}</h3><Badge theme="gray">{{l('SAP 原值只读','SAP originals read-only')}}</Badge></div>
    <div class="ops-scroll"><table class="ops-facts-table"><thead><tr><th>{{l('字段','Field')}}</th><th>SAP</th><th>{{l('业务／SO','Business / SO')}}</th><th>{{l('采用口径','Adopted basis')}}</th></tr></thead><tbody><tr v-for="f in factsFor(order,shipments)" :key="f.field.en"><td>{{tr(f.field)}}</td><td>{{tr(f.sap)}}</td><td>{{tr(f.business)}}<small>{{tr(f.source)}}</small></td><td>{{tr(f.adopted)}}</td></tr></tbody></table></div>
    <p class="ops-note">{{l('初始化来源截至','Initial source as of')}} {{order.sourceAsOf||'—'}} · {{l('SAP 快照日期','SAP snapshot date')}} {{order.sapAsOf||'—'}} · {{l('同步时间','Sync time')}} {{order.syncedAt||'—'}}</p>
    <div class="ops-inline-note"><span>{{l('货值覆盖','Value coverage')}}</span><b>{{l(priceReady(order)?'采用已确认 AUD 采购价格':'该行暂未纳入已确认货值',priceReady(order)?'Confirmed AUD PO price':'Excluded from confirmed value')}}</b></div>
  </template>
  <template v-if="tab==='commitment'">
    <div class="ops-record-refs"><div><small>{{l('原约定发运','Original agreed dispatch')}}</small><b>{{order.initialEtd||'—'}}</b></div><div><small>{{l('最新承诺发运','Latest dispatch commitment')}}</small><b>{{order.promisedEtd||'TBD'}}</b></div><div><small>{{l('国内到货 · ETA China','China inbound ETA')}}</small><b>{{order.chinaEta||'—'}}</b></div><div><small>{{l('澳洲到仓承诺','AU arrival commitment')}}</small><b>{{order.eta||'—'}}</b></div></div>
    <details class="ops-definitions" open><summary>{{l('维护交期与发运延期','Edit dates & dispatch delay')}}</summary><div class="ops-form-grid"><label>{{l('承诺发运日期','Promised dispatch')}}<input v-model="etd" type="date"/></label><label>{{l('国内到货日期','China inbound date')}}<input v-model="china" type="date"/></label><label v-if="order.imported">{{l('澳洲预计到仓 ETA','Estimated AU arrival ETA')}}<input v-model="auEta" type="date"/></label></div><label class="ops-form-label">{{l('发运延期状态','Dispatch delay status')}}<select v-model="delayStatus"><option value="unknown">{{l('待确认','Unconfirmed')}}</option><option value="normal">{{l('正常','On track')}}</option><option value="delayed">{{l('已知延期','Known delay')}}</option></select></label><label class="ops-form-label">{{l('延期原因','Delay reason')}}<textarea v-model="delayReason" rows="2"></textarea></label><label class="ops-form-label">{{l('剩余数量处理安排','Plan for remaining quantity')}}<textarea v-model="plan" rows="2"></textarea></label><label class="ops-form-label">{{l('本次更新说明（必填）','Update note (required)')}}<textarea v-model="reason" rows="2"></textarea></label><p v-if="error" class="ops-error" role="alert">{{error}}</p><Button variant="outline" @click="save">{{l('保存协作日期','Save collaboration dates')}}</Button><p v-if="!order.imported">{{l('这些日期不会替换澳洲到仓承诺；到仓变更仍走下方审核流程。','These dates do not replace the AU arrival commitment; arrival changes use the approval flow below.')}}</p></details>
  </template>
  <template v-if="tab==='logistics'">
    <div class="ops-detail-heading"><h3>{{l('装运分配与收货','Shipment allocations & receipts')}}</h3><Button variant="outline" @click="emit('dispatch',order)">{{l('登记业务报发','Record dispatch')}}</Button></div>
    <div v-for="s in relatedShipments(order,shipments)" :key="s.id" class="ops-panel ops-detail-batch"><header><h3>{{s.id}}</h3><Badge :theme="s.sapPosted?'green':'orange'">{{l(s.sapPosted?'已关联 SAP 过账':'业务报发 · 待核实',s.sapPosted?'SAP PGI linked':'Reported · unverified')}}</Badge></header><div class="ops-record-refs"><div><small>{{l('集装箱号','Container number')}}</small><b>{{s.containerNo||'—'}}</b></div><div><small>{{l('提单／空运单号','B/L / air waybill')}}</small><b>{{s.waybillNo||'—'}}</b></div><div><small>{{l('快递号／承运商','Courier number / carrier')}}</small><b>{{s.courierNo||'—'}} / {{tr(s.carrier)||'—'}}</b></div><div><small>{{l('车架／装载位置','Chassis / loading position')}}</small><b>{{s.chassis||'—'}} / {{tr(s.position)||'—'}}</b></div><div><small>{{l('业务报发／SAP 过账','Report / SAP PGI')}}</small><b>{{s.reportedAt||s.etd}} / {{s.pgiAt||'—'}}</b></div><div><small>{{l('澳洲到仓 ETA','AU warehouse ETA')}}</small><b>{{s.eta||l('待补充','Not provided')}}</b><small>{{l('首次 ETA','First ETA')}} {{s.originalEta||'—'}}</small><small v-if="shipmentDelayed(s)" class="ops-amber">{{l('延期跟进','Delay follow-up')}} {{delayDays(s)>0?'+'+delayDays(s)+'d':''}}</small></div></div><div class="ops-inline-note" v-for="a in allocations(s).filter(a=>a.order===order.id)" :key="a.order"><span>{{l('本行分配／已关联收货','This line allocated / received')}}</span><b>{{a.qty}} / {{a.receivedQty??'—'}} {{order.unit||'EA'}}</b></div><p class="ops-note">{{l('批次关联订单行','Order lines in this batch')}}: {{allocations(s).length}} · {{tr(s.location)}}</p><p v-if="s.delayReason||s.nextAction" class="ops-note">{{l('延期原因／下一步','Delay reason / next action')}}: {{s.delayReason||'—'}} / {{s.nextAction||'—'}}</p><Button variant="outline" @click="emit('shipment',s)">{{l('维护物流与延期','Edit logistics & delay')}}</Button><details v-if="s.updates?.length" class="ops-definitions ops-update-history"><summary>{{l('物流修改历史','Logistics change history')}} · {{s.updates.length}}</summary><article v-for="(u,index) in s.updates" :key="index"><b>{{u.at}}</b><p>{{u.note}}</p><p v-for="(field,k) in SHIPMENT_FIELDS" :key="k" v-show="u.before[k]!==u.after[k]">{{tr(field)}}: {{tr(u.before[k])||'—'}} → {{tr(u.after[k])||'—'}}</p></article></details></div>
    <p v-if="!relatedShipments(order,shipments).length" class="ops-empty">{{l('暂无装运记录，可登记首个报发批次。','No shipments yet. Record the first dispatch batch.')}}</p>
  </template>
  <template v-if="tab==='activity'">
    <div class="ops-detail-heading"><h3>{{l('关联核对任务','Linked review tasks')}}</h3><small>{{issues.length}} {{l('项','tasks')}}</small></div>
    <div class="ops-record-case" v-for="c in issues" :key="c.id"><div><b>{{tr(c.title)}}</b><small>{{c.owner}} · {{c.due}} · {{tr(c.status)}}</small><p>{{c.userEntered?c.detail:tr(c.detail)}}</p><p v-if="c.note">{{c.rule||c.noteUserEntered?c.note:tr(c.note)}}</p><p v-if="c.closure" class="ops-green">{{tr(c.closure)}}</p><details v-if="c.log?.length"><summary>{{l('处理历史','Review history')}}</summary><p v-for="(entry,i) in c.log" :key="i">{{entry.at}} · {{entry.text}}</p></details></div><Button v-if="c.status!=='已解决'" variant="outline" @click="emit('review',c)">{{l('跟进','Review')}}</Button></div><p v-if="!issues.length" class="ops-note">{{l('暂无关联任务','No linked tasks')}}</p>
  </template>
</div></template>
