SELECT H.VBELN,H.WADAT_IST,H.LFDAT,H.VSTEL,H.KUNNR,I.POSNR,I.MATNR,I.LFIMG,I.VRKME,I.VGBEL,I.VGPOS,I.WERKS
FROM SAPHANADB.LIKP H JOIN SAPHANADB.LIPS I ON H.MANDT=I.MANDT AND H.VBELN=I.VBELN
JOIN SAPHANADB.VBAK S ON S.MANDT=I.MANDT AND S.VBELN=I.VGBEL
WHERE H.MANDT='{client}' AND S.VKORG='{salesOrg}' AND S.KUNNR='{customer}'
