SELECT S.EBELN,S.EBELP,S.ZEKKN,S.VGABE,S.GJAHR,S.BELNR,S.BUZEI,S.BWART,S.BUDAT,S.MENGE,S.SHKZG,S.WAERS
FROM SAPHANADB.EKBE S JOIN SAPHANADB.EKKO H ON H.MANDT=S.MANDT AND H.EBELN=S.EBELN
JOIN SAPHANADB.EKPO I ON I.MANDT=S.MANDT AND I.EBELN=S.EBELN AND I.EBELP=S.EBELP
WHERE S.MANDT='{client}' AND H.BUKRS='{company}' AND I.WERKS='{plant}' AND H.LIFNR='{supplier}'
