SELECT H.EBELN,H.BUKRS,H.BSART,H.EKORG,H.EKGRP,H.LIFNR,H.BEDAT,H.WAERS,H.RESWK,I.EBELP,I.MATNR,I.TXZ01,I.WERKS,I.LGORT,I.MENGE,I.MEINS,I.NETPR,I.PEINH,I.NETWR,I.LOEKZ,I.ELIKZ
FROM SAPHANADB.EKKO H JOIN SAPHANADB.EKPO I ON H.MANDT=I.MANDT AND H.EBELN=I.EBELN
WHERE H.MANDT='{client}' AND H.BUKRS='{company}' AND I.WERKS='{plant}' AND H.LIFNR='{supplier}'
