SELECT S.EBELN,S.EBELP,S.ETENR,S.EINDT,S.MENGE,S.WEMNG
FROM SAPHANADB.EKET S JOIN SAPHANADB.EKKO H ON H.MANDT=S.MANDT AND H.EBELN=S.EBELN
JOIN SAPHANADB.EKPO I ON I.MANDT=S.MANDT AND I.EBELN=S.EBELN AND I.EBELP=S.EBELP
WHERE S.MANDT='{client}' AND H.BUKRS='{company}' AND I.WERKS='{plant}' AND H.LIFNR='{supplier}'
