SELECT H.VBELN,H.VKORG,H.AUART,H.VTWEG,H.KUNNR,H.ERDAT,H.BSTNK,H.VDATU,H.WAERK,I.POSNR,I.MATNR,I.ARKTX,I.KWMENG,I.VRKME,I.WERKS,I.POSEX,I.NETWR,I.ABGRU
FROM SAPHANADB.VBAK H JOIN SAPHANADB.VBAP I ON H.MANDT=I.MANDT AND H.VBELN=I.VBELN
WHERE H.MANDT='{client}' AND H.VKORG='{salesOrg}' AND H.KUNNR='{customer}'
